"""M_HW_TrailAdditive (docs/design/171): the weapon trail's segments - additive, unlit, Color x Glow, faded by the particle colour and across the ribbon width.
Paragon's trails are AnimTrail emitters that need the pack's anim notifies; the hero trail is drawn from segments.

UnrealEditor-Cmd <uproject> -ExecutePythonScript="Scripts/ue_fx_trail_material.py" -unattended -nullrhi
"""
import unreal

PATH, NAME = "/Game/Hwanghon/VFX", "M_HW_TrailAdditive"
lib = unreal.MaterialEditingLibrary
if unreal.EditorAssetLibrary.does_asset_exist(f"{PATH}/{NAME}"):
    unreal.EditorAssetLibrary.delete_asset(f"{PATH}/{NAME}")
mat = unreal.AssetToolsHelpers.get_asset_tools().create_asset(NAME, PATH, unreal.Material, unreal.MaterialFactoryNew())
mat.set_editor_property("blend_mode", unreal.BlendMode.BLEND_ADDITIVE)
mat.set_editor_property("shading_model", unreal.MaterialShadingModel.MSM_UNLIT)
mat.set_editor_property("two_sided", True)
color = lib.create_material_expression(mat, unreal.MaterialExpressionVectorParameter, -700, 0)
color.set_editor_property("parameter_name", "Color")
color.set_editor_property("default_value", unreal.LinearColor(r=1.0, g=0.55, b=0.12, a=1.0))
glow = lib.create_material_expression(mat, unreal.MaterialExpressionScalarParameter, -700, 200)
glow.set_editor_property("parameter_name", "Glow")
glow.set_editor_property("default_value", 4.0)
# the ribbon fades along its life (ParticleColor from the trail emitter) and across its width (bright centre line):
# edge = 1 - |2v - 1|, mixed in by EdgeMix (1 on a trail ribbon, 0 on the projectile orb, a plain mesh)
pc = lib.create_material_expression(mat, unreal.MaterialExpressionParticleColor, -700, 350)
tc = lib.create_material_expression(mat, unreal.MaterialExpressionTextureCoordinate, -900, 550)
mask = lib.create_material_expression(mat, unreal.MaterialExpressionComponentMask, -760, 550)
mask.set_editor_property("r", False); mask.set_editor_property("g", True)
lib.connect_material_expressions(tc, "", mask, "")
two = lib.create_material_expression(mat, unreal.MaterialExpressionMultiply, -640, 550)
two.set_editor_property("const_b", 2.0)
lib.connect_material_expressions(mask, "", two, "A")
sub = lib.create_material_expression(mat, unreal.MaterialExpressionSubtract, -540, 550)
sub.set_editor_property("const_b", 1.0)
lib.connect_material_expressions(two, "", sub, "A")
ab = lib.create_material_expression(mat, unreal.MaterialExpressionAbs, -440, 550)
lib.connect_material_expressions(sub, "", ab, "")
edge = lib.create_material_expression(mat, unreal.MaterialExpressionOneMinus, -340, 550)
lib.connect_material_expressions(ab, "", edge, "")
mix = lib.create_material_expression(mat, unreal.MaterialExpressionScalarParameter, -340, 700)
mix.set_editor_property("parameter_name", "EdgeMix")
mix.set_editor_property("default_value", 1.0)
lerp = lib.create_material_expression(mat, unreal.MaterialExpressionLinearInterpolate, -220, 550)
lerp.set_editor_property("const_a", 1.0)
lib.connect_material_expressions(edge, "", lerp, "B")
lib.connect_material_expressions(mix, "", lerp, "Alpha")
m1 = lib.create_material_expression(mat, unreal.MaterialExpressionMultiply, -350, 100)
lib.connect_material_expressions(color, "", m1, "A")
lib.connect_material_expressions(glow, "", m1, "B")
m2 = lib.create_material_expression(mat, unreal.MaterialExpressionMultiply, -220, 200)
lib.connect_material_expressions(m1, "", m2, "A")
lib.connect_material_expressions(pc, "", m2, "B")        # rgb tint x
m3 = lib.create_material_expression(mat, unreal.MaterialExpressionMultiply, -120, 300)
lib.connect_material_expressions(m2, "", m3, "A")
lib.connect_material_expressions(pc, "A", m3, "B")       # life fade
m4 = lib.create_material_expression(mat, unreal.MaterialExpressionMultiply, -20, 400)
lib.connect_material_expressions(m3, "", m4, "A")
lib.connect_material_expressions(lerp, "", m4, "B")
lib.connect_material_property(m4, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
mat.set_editor_property("used_with_particle_sprites", True)
mat.set_editor_property("used_with_beam_trails", True)
mat.set_editor_property("used_with_static_lighting", False)
lib.recompile_material(mat)
unreal.EditorAssetLibrary.save_asset(f"{PATH}/{NAME}")

# M_HW_ParticleTint (docs/design/171 §2): the Paragon particles in the hero's colour. The packs are red (Countess),
# fire (Grux) and green (Sevarog) - no steel, no blue. An emitter keeps its own texture (shape, flipbook) and its
# particle colour's brightness and life fade; only the hue becomes Color.
NAME2 = "M_HW_ParticleTint"
if unreal.EditorAssetLibrary.does_asset_exist(f"{PATH}/{NAME2}"):
    unreal.EditorAssetLibrary.delete_asset(f"{PATH}/{NAME2}")
mt = unreal.AssetToolsHelpers.get_asset_tools().create_asset(NAME2, PATH, unreal.Material, unreal.MaterialFactoryNew())
mt.set_editor_property("blend_mode", unreal.BlendMode.BLEND_ADDITIVE)
mt.set_editor_property("shading_model", unreal.MaterialShadingModel.MSM_UNLIT)
mt.set_editor_property("two_sided", True)
for flag in ("used_with_particle_sprites", "used_with_beam_trails", "used_with_mesh_particles", "used_with_static_lighting"):
    mt.set_editor_property(flag, flag != "used_with_static_lighting")
tex = lib.create_material_expression(mt, unreal.MaterialExpressionTextureSampleParameterSubUV, -900, 0)
tex.set_editor_property("parameter_name", "Tex")
tex.set_editor_property("texture", unreal.load_asset("/Engine/EngineResources/DefaultTexture"))
third = lib.create_material_expression(mt, unreal.MaterialExpressionConstant3Vector, -900, 300)
third.set_editor_property("constant", unreal.LinearColor(r=0.4, g=0.4, b=0.4, a=1.0))
tl = lib.create_material_expression(mt, unreal.MaterialExpressionDotProduct, -650, 0)
lib.connect_material_expressions(tex, "RGB", tl, "A")
lib.connect_material_expressions(third, "", tl, "B")
pcol = lib.create_material_expression(mt, unreal.MaterialExpressionParticleColor, -900, 450)
pl = lib.create_material_expression(mt, unreal.MaterialExpressionDotProduct, -650, 400)
lib.connect_material_expressions(pcol, "RGB", pl, "A")
lib.connect_material_expressions(third, "", pl, "B")
k1 = lib.create_material_expression(mt, unreal.MaterialExpressionMultiply, -500, 100)
lib.connect_material_expressions(tl, "", k1, "A")
lib.connect_material_expressions(tex, "A", k1, "B")
k2 = lib.create_material_expression(mt, unreal.MaterialExpressionMultiply, -500, 400)
lib.connect_material_expressions(pl, "", k2, "A")
lib.connect_material_expressions(pcol, "A", k2, "B")
k3 = lib.create_material_expression(mt, unreal.MaterialExpressionMultiply, -350, 250)
lib.connect_material_expressions(k1, "", k3, "A")
lib.connect_material_expressions(k2, "", k3, "B")
col = lib.create_material_expression(mt, unreal.MaterialExpressionVectorParameter, -500, -200)
col.set_editor_property("parameter_name", "Color")
col.set_editor_property("default_value", unreal.LinearColor(r=0.12, g=0.45, b=1.0, a=1.0))
gl = lib.create_material_expression(mt, unreal.MaterialExpressionScalarParameter, -500, -50)
gl.set_editor_property("parameter_name", "Glow")
gl.set_editor_property("default_value", 1.0)
c1 = lib.create_material_expression(mt, unreal.MaterialExpressionMultiply, -350, -120)
lib.connect_material_expressions(col, "", c1, "A")
lib.connect_material_expressions(gl, "", c1, "B")
out = lib.create_material_expression(mt, unreal.MaterialExpressionMultiply, -180, 50)
lib.connect_material_expressions(c1, "", out, "A")
lib.connect_material_expressions(k3, "", out, "B")
lib.connect_material_property(out, "", unreal.MaterialProperty.MP_EMISSIVE_COLOR)
lib.recompile_material(mt)
unreal.EditorAssetLibrary.save_asset(f"{PATH}/{NAME2}")
