// Online menus use server-owned profiles. No values from the solo save are imported.
export function createRpgUI(api){
 const $=id=>document.getElementById(id),items=window.TW_ITEMS;
 const el=(tag,text,cls)=>{const n=document.createElement(tag);if(text!=null)n.textContent=text;if(cls)n.className=cls;return n;};
 const button=(text,fn,disabled=false)=>{const n=el('button',text);n.type='button';n.disabled=disabled;n.onclick=fn;return n;};
 const field=(label,type='text',value='')=>{const wrap=el('label',label),input=el('input');input.type=type;input.value=value;wrap.append(input);return {wrap,input};};
 const select=(label,options,value)=>{const wrap=el('label',label),input=el('select');for(const [key,name]of options){const opt=el('option',name);opt.value=key;input.append(opt);}if(value!=null)input.value=value;wrap.append(input);return {wrap,input};};
 const name=id=>items.get(id)?.name||id;
 const fmt=n=>Number(n||0).toLocaleString();
 const loot=list=>list.map(([id,n])=>name(id)+' × '+n).join(', ');
 let data=null,profile=null,tab='quests',guild=null,filter='',category='all',bagMode='bag',sort='name',admin=null;
 let settings={volume:.7,camera:1,zoom:1,effects:1,shake:false,buttons:1,offset:0,font:1,attack:'KeyJ',dodge:'KeyK',guard:'KeyL',forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD'};
 try{settings={...settings,...JSON.parse(localStorage.getItem('tw:online-settings')||'{}')};}catch{}
 const validKeys=new Set(['KeyJ','KeyK','KeyL','KeyU','KeyF','KeyV','KeyR','KeyW','KeyA','KeyS','KeyD','KeyZ','KeyX','KeyC','KeyE','Space']);
 for(const [key,lo,hi]of [['volume',0,1],['camera',.4,2],['zoom',.75,1.5],['effects',0,1],['buttons',.8,1.3],['offset',0,90],['font',.85,1.3]])settings[key]=Math.max(lo,Math.min(hi,Number.isFinite(settings[key])?settings[key]:1));
 for(const key of ['attack','dodge','guard','forward','back','left','right'])if(!validKeys.has(settings[key]))settings[key]={attack:'KeyJ',dodge:'KeyK',guard:'KeyL',forward:'KeyW',back:'KeyS',left:'KeyA',right:'KeyD'}[key];
 const dialog=el('dialog',null,'rpg-dialog');dialog.id='rpg-dialog';
 const header=el('div',null,'panel-title'),title=el('h2','출격자 수첩');header.append(title,button('닫기',()=>dialog.close()));
 const tabs=el('nav',null,'rpg-tabs'),body=el('div',null,'rpg-body'),status=el('p','','rpg-status');status.setAttribute('role','status');dialog.append(header,tabs,status,body);document.body.append(dialog);
 const secretDialog=el('dialog',null,'rpg-dialog'),secretCode=el('code'),secretText=el('p','이 복구 코드는 다시 표시되지 않습니다. 다른 기기에도 안전하게 보관하세요. 사용하거나 비밀번호를 바꾸면 이전 코드는 폐기됩니다.');secretDialog.append(el('h2','계정 복구 코드'),secretText,secretCode,button('복사',async()=>{try{await navigator.clipboard.writeText(secretCode.textContent);}catch{secretText.textContent='코드를 직접 선택해 복사하세요.';}}),button('보관했습니다',()=>{secretDialog.close();secretCode.textContent='';}));document.body.append(secretDialog);
 const invitationDialog=el('dialog',null,'rpg-dialog');document.body.append(invitationDialog);
 const mainButtons=el('div',null,'town-tabs');for(const [key,label]of [['quests','의뢰'],['inventory','가방·보관함'],['craft','제작·강화'],['build','기술·출정'],['social','동료'],['settings','설정'],['account','계정']])mainButtons.append(button(label,()=>open(key)));$('hub-tools').prepend(mainButtons);
 $('raid-menu').append(button('설정',()=>{$('raid-menu').close();open('settings');}),button('동료·귓속말',()=>{$('raid-menu').close();open('social');}));
 $('login').append(button('복구 코드로 비밀번호 재설정',()=>open('recover')));
 const whisper=el('option','귓속말');whisper.value='whisper';$('chat-channel').append(whisper);const target=el('input');target.id='whisper-target';target.placeholder='받는 캐릭터 이름';target.maxLength=16;target.setAttribute('aria-label','귓속말 대상');target.hidden=true;$('chat-form').prepend(target);$('chat-channel').addEventListener('change',()=>target.hidden=$('chat-channel').value!=='whisper');
 const purpose=select('모집 목적',[['first','첫 클리어'],['practice','연습'],['repeat','반복 토벌']],'first');purpose.input.id='party-purpose';$('choose-room').prepend(purpose.wrap);
 const briefing=el('p','','subtle');briefing.id='dungeon-brief';$('choose-room').append(briefing);$('dungeon').addEventListener('change',dungeonBrief);
 const roomTools=el('div',null,'rpg-room-tools');$('room').append(roomTools);
 const utility=el('div',null,'rpg-utility');utility.id='rpg-utility';for(let slot=0;slot<2;slot++){const b=button('소모품 '+(slot+1),()=>send('useItem',{slot}));b.id='quick-item-'+slot;utility.append(b);}const ping=select('전술 신호',[['focus','이 부위 집중'],['danger','위험'],['revive','소생 요청'],['gather','집결']]);utility.append(ping.wrap,button('신호',()=>send('signal',{signal:ping.input.value})));$('arena').append(utility);
 const feedback=el('div',null,'rpg-feedback');feedback.id='rpg-feedback';feedback.setAttribute('role','status');$('arena').append(feedback);
 function send(action,fields={}){api.send({type:'rpg',action,...fields});}
 function applySettings(){for(const action of ['attack','dodge','guard']){const button=document.querySelector('[data-command='+action+']');if(button)button.textContent=({attack:'공격',dodge:'회피',guard:'카운터·방어'}[action])+' '+settings[action].replace('Key','');}document.documentElement.style.setProperty('--rpg-buttons',settings.buttons);document.documentElement.style.setProperty('--rpg-offset',settings.offset+'px');document.documentElement.style.setProperty('--rpg-font',settings.font);if(window.TW_SFX)window.TW_SFX.volume=settings.volume;try{localStorage.setItem('tw:online-settings',JSON.stringify(settings));}catch{}}
 applySettings();
 function open(key){tab=key;api.clearControls();status.textContent='';if(!dialog.open)dialog.showModal();render();if(profile?.characterCreated&&key!=='settings'&&key!=='recover')send('state');}
 function info(text){status.textContent=text;}
 function card(title,text){const c=el('section',null,'rpg-card');c.append(el('h3',title));if(text)c.append(el('p',text));body.append(c);return c;}
 function render(){tabs.replaceChildren();for(const [key,label]of [['quests','의뢰'],['inventory','가방'],['craft','제작·강화'],['build','기술·출정'],['social','동료'],['settings','설정'],['account','계정'],...(data?.admin?[['admin','운영']]:[])]){const b=button(label,()=>{tab=key;status.textContent='';render();});b.setAttribute('aria-pressed',String(tab===key));tabs.append(b);}body.replaceChildren();title.textContent=tab==='recover'?'계정 복구':'출격자 수첩';
  if(tab==='settings'){renderSettings();return;}if(tab==='recover'){renderRecovery();return;}if(!profile||!data){body.append(el('p','접속 후 정보를 불러옵니다.'));return;}
  if(api.getRoom()?.raid&&!['social','account','admin'].includes(tab)){body.append(el('p','정비 메뉴는 인력사무소에서 이용할 수 있습니다.'));return;}
  ({quests:renderQuests,inventory:renderInventory,craft:renderCraft,build:renderBuild,social:renderSocial,account:renderAccount,admin:renderAdmin})[tab]?.();
 }
 function renderQuests(){if(data.notice)card('서버 공지',data.notice);for(const q of data.quests){const labels={locked:'잠김',available:'수락 가능',active:'수행 중',complete:'보수 수령 가능',claimed:'완료'};const c=card(q.name+' · '+labels[q.status],q.status==='claimed'?q.after:q.brief);c.append(el('p',fmt(q.gold)+' G · '+q.xp+' XP · '+loot(q.items)));if(q.previous&&q.status==='locked')c.append(el('p','이전 의뢰 보수를 수령하면 해금됩니다.'));if(q.status==='available')c.append(button('의뢰 수락',()=>send('quest',{quest:q.id,operation:'accept'})));if(q.status==='complete')c.append(button('보수 수령',()=>send('quest',{quest:q.id,operation:'claim'})));if(['active','claimed'].includes(q.status))c.append(button('이 지역 모집 준비',()=>{$('dungeon').value=q.level;dungeonBrief();dialog.close();$('choose-room').scrollIntoView({behavior:'smooth'});}));}
  const mail=card('전리품·전투 기록','던전 보상은 개인별 자동 지급됩니다. 첫 클리어와 팀 부위 파괴 보너스를 함께 확인하세요.');mail.append(button('미수령 보상 다시 받기',()=>send('claimRewards')));for(const m of data.mail){const details=el('details'),r=m.reward;details.append(el('summary',(m.delivered?'지급 완료 · ':'미수령 · ')+(window.TW_DUNGEONS.ARENAS[m.arena]?.name||m.arena)+' · '+new Date(m.created).toLocaleString()));details.append(el('p',fmt(r.gold+(r.firstGold||0))+' G · '+loot([...r.items,...(r.bonusItems||[])])));if(r.record)details.append(el('p',recordText(r.record)));mail.append(details);}if(!data.mail.length)mail.append(el('p','아직 클리어 기록이 없습니다.'));if(data.interrupted.length)card('중단된 출격','서버 재시작으로 진행 중인 던전은 종료되었습니다. 완료가 확정된 보상은 우편에서 복구됩니다. 중단된 전투는 재출정해야 합니다.');
 }
 function renderInventory(){
  const toolbar=el('div',null,'rpg-form');const find=field('이름 검색','search',filter),type=select('분류',[['all','전체'],['weapon','무기'],['armor','방어구'],['acc','장신구'],['material','재료'],['consumable','소모품'],['quest','의뢰품']],category),mode=select('위치',[['bag','가방'],['vault','개인 보관함']],bagMode),order=select('정렬',[['name','이름'],['quantity','수량']],sort);toolbar.append(find.wrap,type.wrap,mode.wrap,order.wrap);body.append(toolbar);const list=el('div');body.append(list);
  function draw(){list.replaceChildren();const source=bagMode==='bag'?profile.items:profile.vault;const entries=Object.entries(source||{}).filter(([id,n])=>n>0&&(category==='all'||items.get(id)?.type===category)&&name(id).includes(filter)).sort((a,b)=>sort==='quantity'?b[1]-a[1]:name(a[0]).localeCompare(name(b[0])));for(const [id,n]of entries){const item=items.get(id),gear=data.equipment.find(e=>e.id===id),equipped=Object.values(profile.equipment).includes(id),locked=profile.locks[id];const row=el('section',null,'rpg-card');row.append(el('h3',name(id)+' × '+n+(equipped?' · 착용':'')+(locked?' · 잠금':'')));const count=field('수량','number','1');count.input.min=1;count.input.max=n;row.append(count.wrap);
   if(gear){if(gear.effect)row.append(el('p',gear.effect));row.append(el('p','요구 Lv.'+gear.level+' · 강화 +'+gear.enh+' · 내구도 '+gear.dur+'/100'));row.append(el('p','교체 시 변화: 체력 '+signed(gear.comparison.hp-profile.stats.hp)+' / 공격 '+signed(gear.comparison.atk-profile.stats.atk)+' / 방어 '+signed(gear.comparison.defense-profile.stats.defense)+' / 치명타 확률 '+signed(Math.round((gear.comparison.critChance-profile.stats.critChance)*1000)/10)+'%p'));if(bagMode==='bag'){row.append(button(locked?'잠금 해제':'장비 잠금',()=>send('lock',{item:id})));if(!equipped)row.append(button('착용',()=>api.send({type:'equip',item:id}),profile.level<gear.level));else if(item.slot!=='main')row.append(button('착용 해제',()=>send('unequip',{item:id})));}}
   if(bagMode==='vault')row.append(button('꺼내기',()=>send('withdraw',{item:id,quantity:Number(count.input.value)})));else {row.append(button('보관',()=>send('deposit',{item:id,quantity:Number(count.input.value)}),equipped||locked||item?.type==='quest'));const unit=items.SHOP.find(s=>s.id===id)?.sell||(gear?Math.floor(item.price*.2):0);const danger=el('details');danger.append(el('summary','판매·분해'));danger.append(el('p','판매 단가 '+fmt(unit)+' G. 선택한 물품을 소모합니다. 장비 강화와 내구도 정보도 삭제됩니다.'));danger.append(button('선택 수량 판매',()=>send('vendorSell',{item:id,quantity:Number(count.input.value)}),equipped||locked||item?.type==='quest'));if(gear)danger.append(button('장비 1개 분해',()=>send('dismantle',{item:id,quantity:1}),equipped||locked));row.append(danger);}list.append(row);}if(!entries.length)list.append(el('p','해당 물품이 없습니다.'));}
  find.input.oninput=()=>{filter=find.input.value;draw();};type.input.onchange=()=>{category=type.input.value;draw();};mode.input.onchange=()=>{bagMode=mode.input.value;draw();};order.input.onchange=()=>{sort=order.input.value;draw();};draw();
 }
 function signed(n){return (n>=0?'+':'')+fmt(n);}
 function renderCraft(){card('공방','제작은 즉시 완료됩니다. 장비는 종류별 하나를 보유하며, 강화·수리 상태가 저장됩니다. 강화는 +1부터 실패할 수 있습니다. 실패 시 단계와 내구도가 감소하며, 내구도 0에서는 성능이 절반이 됩니다. 수리하여 복구할 수 있습니다.');
  for(const r of data.recipes){const c=card(name(r.result)+' 제작','요구 Lv.'+r.level+' · '+fmt(r.cost)+' G · 결과 '+(r.yield||1)+'개');c.append(el('p',r.mats.map(([id,n])=>name(id)+' '+(profile.items[id]||0)+'/'+n).join(' · ')));const enough=profile.level>=r.level&&profile.gold>=r.cost&&r.mats.every(([id,n])=>profile.items[id]>=n);c.append(button('제작',()=>send('craft',{recipe:r.id}),!enough));}
  for(const g of data.equipment.filter(g=>profile.items[g.id]>0)){const c=card(name(g.id)+' +'+g.enh,'내구도 '+g.dur+'/100');c.append(button('수리 · '+fmt(g.repairCost)+' G',()=>send('repair',{item:g.id}),g.dur===100));const q=g.quote;if(q){c.append(el('p','다음 +'+q.to+' · 성공 '+q.rate+'% · '+fmt(q.cost)+' G · '+loot(q.mats)));c.append(el('p','실패 시 '+q.drop+'단계 하락 · 내구도 -'+q.durLoss+' · 실패 보정 현재 +'+profile.failstack+'%p'));const protect=field('강화 보조제 '+q.booster+'개 사용 · 실패 시 단계 하락 방지','checkbox');protect.input.checked=false;c.append(protect.wrap,button('비용을 소모하여 강화',()=>send('enhance',{item:g.id,protect:protect.input.checked}),g.dur<20));}}
 }
 function renderBuild(){const c=card((data.skills?.characterName||'출격자')+'의 전투 특성','장비와 특성 변경은 다음 출정부터 반영됩니다. 준비 완료 상태가 해제됩니다.');for(const [id,t]of Object.entries(data.traits))c.append(button(t.name+' · '+t.description+(profile.trait===id?' (선택됨)':''),()=>send('trait',{trait:id}),profile.trait===id));
  const prep=card('소모품 준비','회복약: 체력 35% 회복 / 지혈제: 출혈 해제 / 폭약: 부위 피해. 종류별 출격당 최대 3회, 공통 20초 재사용 시간. 사용 즉시 가방에서 차감됩니다.');const opts=['c_potion','c_antidote','c_throw'].map(id=>[id,name(id)+' · '+(profile.items[id]||0)+'개']);const a=select('퀵슬롯 1',opts,profile.quickslots[0]),b=select('퀵슬롯 2',opts,profile.quickslots[1]);prep.append(a.wrap,b.wrap,button('퀵슬롯 저장',()=>send('quickslots',{slots:[a.input.value,b.input.value]})),button('보급소 열기',()=>{dialog.close();$('open-shop').click();}));
  const sk=data.skills;
  const tree=card('기술 성장 · '+(sk?('포인트 '+sk.points.free+' / '+sk.points.total):'불러오는 중'),'강화는 서버가 기록하고 다음 출정부터 적용됩니다. 분기는 '+(sk?sk.branchLevel:3)+'단계부터 고를 수 있고, 바꾸려면 초기화해야 합니다.');
  if(sk){for(const k of sk.skills){
    const row=el('div',null,'rpg-card');
    row.append(el('h3',(k.ult?'궁극기 · ':'')+k.name+' · Lv'+k.lv+(k.br?' · '+k.br:'')+(k.lv>=sk.max?' (최대)':'')));
    row.append(el('p',k.desc||''));
    row.append(el('p','현재 — '+(k.summary||'—')));
    if(k.next)row.append(el('p','다음 — '+k.next));
    row.append(button('강화 (1 포인트)',()=>send('skillUp',{skill:k.id}),k.lv>=sk.max||sk.points.free<1));
    if(k.lv>=sk.branchLevel&&!k.br)for(const b of ['A','B'])row.append(button('분기 '+b+' · '+k.branches[b].name+' — '+k.branches[b].label,()=>send('skillBranch',{skill:k.id,branch:b}),sk.points.free<1));
    tree.append(row);
  }
  tree.append(button('기술 초기화 · '+fmt(sk.resetCost)+' G',()=>send('skillReset'),sk.points.spent<1||profile.gold<sk.resetCost));}
  const skills=card('전투 요령','일반 공격으로 거리를 재고, 카운터·회피 반격·부분 파괴로 큰 피해를 주는 전투입니다.');skills.append(el('p','카운터: 공격 예고 끝에 공격 / 회피 반격: 실제 공격을 피한 후 0.85초 안에 공격 / 궁극기: 전투로 게이지를 채워 사용'));
  const training=card('허수아비 패턴 훈련','선택한 공격을 반복합니다. 개인 훈련에는 보상과 의뢰 진행이 없습니다. 소모품은 실제 보유분을 사용합니다.');const patterns=[];window.TW_DUNGEONS.ARENAS.tutorial.stages.forEach((stage,i)=>stage.patterns.forEach((p,j)=>patterns.push([i+':'+j,stage.name+' · '+p.name])));const pick=select('훈련할 공격',patterns);training.append(pick.wrap,button('개인 훈련 시작',()=>{const [phase,pattern]=pick.input.value.split(':').map(Number);api.send({type:'training',phase,pattern});},!!api.getRoom()));
 }
 function renderSocial(){const f=card('친구·차단','캐릭터 이름으로 친구 요청을 보내고, 상대가 수락하면 친구가 됩니다.');const who=field('캐릭터 이름');who.input.maxLength=16;f.append(who.wrap,button('친구 요청',()=>send('request',{name:who.input.value})),button('차단',()=>send('block',{name:who.input.value})),button('파티 초대',()=>send('partyInvite',{name:who.input.value}),!api.getRoom()));
  for(const c of data.contacts){const row=el('div',null,'market-row');row.append(el('span',c.name+' · '+(c.kind==='block'?'차단':c.kind==='request'?(c.incoming?'받은 요청':'보낸 요청'):(c.online?'접속 중':'접속 종료'))));if(c.kind==='request'&&c.incoming)row.append(button('수락',()=>send('accept',{target:c.id})));row.append(button(c.kind==='block'?'차단 해제':c.kind==='request'?'요청 취소·거절':'친구 삭제',()=>send(c.kind==='block'?'unblock':'remove',{target:c.id})));f.append(row);}
  const w=card('귓속말','대상에게만 전송됩니다. 상대 또는 내가 차단한 경우 보낼 수 없습니다.');const recipient=field('받는 캐릭터 이름'),message=field('내용');recipient.input.maxLength=16;message.input.maxLength=160;w.append(recipient.wrap,message.wrap,button('보내기',()=>{send('whisper',{name:recipient.input.value,text:message.input.value});message.input.value='';}));
  const report=card('신고','본인이 볼 수 있는 최근 채팅을 서버에서 첨부합니다. 신고만으로 자동 제재되지는 않습니다.');const accused=field('신고할 캐릭터 이름'),reason=field('사유');accused.input.maxLength=16;reason.input.maxLength=240;report.append(accused.wrap,reason.wrap,button('신고 접수',()=>send('report',{name:accused.input.value,reason:reason.input.value})));
  const g=data.guild;if(g){const lounge=card(g.name+' · 길드 공지',g.notice||'등록된 공지가 없습니다.');const me=g.members.find(m=>m.id===profile.id);if(['owner','officer'].includes(me?.role)){const note=field('공지 내용','text',g.notice);note.input.maxLength=240;lounge.append(note.wrap,button('공지 저장',()=>send('guildManage',{operation:'notice',value:note.input.value})));for(const member of g.members.filter(m=>m.id!==profile.id)){const row=el('div',null,'rpg-card');row.append(el('p',member.name+' · '+({owner:'길드장',officer:'간부',member:'길드원'}[member.role])));if(me.role==='owner'){row.append(button(member.role==='officer'?'일반 길드원으로':'간부 임명',()=>send('guildManage',{operation:member.role==='officer'?'member':'officer',target:member.id})));const transfer=el('details');transfer.append(el('summary','길드장 위임'),button('이 길드원에게 위임',()=>send('guildManage',{operation:'transfer',target:member.id})));row.append(transfer);}if(member.role==='member'||me.role==='owner'){const kick=el('details');kick.append(el('summary','추방'),button('추방 확정',()=>send('guildManage',{operation:'kick',target:member.id})));row.append(kick);}lounge.append(row);}}}
 }
 function renderSettings(){const c=card('조작·화면·소리','이 기기에 저장합니다. 전투 중 메뉴를 열어도 다른 플레이어의 전투는 계속됩니다.');for(const [key,label,min,max,step]of [['volume','전체 음량',0,1,.05],['camera','카메라 추적 속도',.4,2,.1],['zoom','카메라 거리',.75,1.5,.05],['effects','타격 섬광 강도',0,1,.1],['buttons','모바일 버튼 크기',.8,1.3,.05],['offset','모바일 버튼 하단 여백',0,90,5],['font','메뉴 글자 크기',.85,1.3,.05]]){const v=field(label,'range',settings[key]);v.input.min=min;v.input.max=max;v.input.step=step;const output=el('output',String(settings[key]));v.input.oninput=()=>{settings[key]=Number(v.input.value);output.textContent=v.input.value;applySettings();};v.wrap.append(output);c.append(v.wrap);}const shake=field('피격 시 카메라 흔들림','checkbox');shake.input.checked=settings.shake;shake.input.onchange=()=>{settings.shake=shake.input.checked;applySettings();};c.append(shake.wrap);
  for(const [key,label]of [['attack','공격'],['dodge','회피'],['guard','방어'],['forward','이동 위'],['back','이동 아래'],['left','이동 왼쪽'],['right','이동 오른쪽']]){const k=select(label,[...validKeys].map(k=>[k,k.replace('Key','')]),settings[key]);k.input.onchange=()=>{const used=Object.entries(settings).some(([other,value])=>other!==key&&['attack','dodge','guard','forward','back','left','right'].includes(other)&&value===k.input.value);if(used||['KeyU','KeyF','KeyV','KeyR'].includes(k.input.value)){info('다른 조작에 배정된 키입니다.');k.input.value=settings[key];return;}api.clearControls();settings[key]=k.input.value;applySettings();info('조작키를 저장했습니다.');};c.append(k.wrap);}
 }
 /* 한글 조사: 받침이 있으면 «으로», 없거나 ㄹ 받침이면 «로» */
 function euro(name){ var ch=name.charCodeAt(name.length-1)-0xAC00; if(ch<0||ch>11171) return '로'; var jong=ch%28; return (jong===0||jong===8)?'로':'으로'; }
 function renderAccount(){card('내 계정','캐릭터 ID: '+profile.id);
  if(data.characters){ const sw=card('출격 캐릭터 변경 · '+fmt(data.switchCost)+' G',
    '계정당 캐릭터는 하나입니다. 골드·재료·장비·의뢰 진행은 그대로 유지되고, 기술은 초기화됩니다(포인트는 돌려받습니다). 새 캐릭터가 들 수 없는 주무기는 가방으로 내려놓고 시작 무기를 줍니다.');
    for(const c of data.characters){ const now=c.id===(data.skills&&data.skills.character);
      sw.append(button(c.name+(now?' · 출격 중':euro(c.name)+' 변경'),()=>send('switchCharacter',{character:c.id}), now||profile.gold<data.switchCost)); } }
const c=card('비밀번호 변경·복구 코드 발급','현재 비밀번호로 확인한 뒤 새 비밀번호와 일회용 복구 코드를 발급합니다. 복구 코드는 계정 비밀번호와 별도로 보관하세요.');const old=field('현재 비밀번호','password'),next=field('새 비밀번호 (10자 이상)','password');old.input.autocomplete='current-password';next.input.autocomplete='new-password';c.append(old.wrap,next.wrap,button('비밀번호 변경 및 복구 코드 발급',()=>{send('password',{current:old.input.value,password:next.input.value});old.input.value=next.input.value='';},!profile.account));}
 function renderRecovery(){const c=card('계정 복구','미리 발급받은 복구 코드가 있어야 합니다. 성공하면 코드가 새로 발급됩니다.');const id=field('계정 ID'),code=field('복구 코드','password'),next=field('새 비밀번호 (10자 이상)','password');c.append(id.wrap,code.wrap,next.wrap,button('복구하고 로그인',()=>{api.connect({type:'account',mode:'recover',username:id.input.value,code:code.input.value,password:next.input.value});code.input.value=next.input.value='';}));}
 function renderAdmin(){if(!data.admin)return;const c=card('운영 기록','신고·제재·경제 작업의 최근 기록을 확인합니다. 운영자 권한은 서버에서 지정합니다.');c.append(button('기록 새로고침',()=>send('adminState')));const notice=field('서버 공지');notice.input.maxLength=240;c.append(notice.wrap,button('공지 게시',()=>send('announcement',{text:notice.input.value})));if(admin){for(const report of admin.reports){const row=el('section',null,'rpg-card');row.append(el('p','#'+report.id+' · '+report.status+' · 대상 '+report.target),el('p',report.reason),el('p',report.evidence));const why=field('제재 사유','text',report.reason);row.append(why.wrap,button('채팅 제한 60분',()=>send('moderate',{operation:'mute',target:report.target,minutes:60,reason:why.input.value})),button('접속 제한 60분',()=>send('moderate',{operation:'ban',target:report.target,minutes:60,reason:why.input.value})),button('제재 해제',()=>send('moderate',{operation:'lift',target:report.target,minutes:1,reason:why.input.value})),button('검토 완료',()=>send('moderate',{operation:'resolve',target:String(report.id),minutes:1,reason:'reviewed'})));c.append(row);}const log=el('pre');log.textContent=JSON.stringify({audit:admin.audit,trades:admin.trades},null,2);c.append(log);}}
 function recordText(r){return '카운터 '+r.counters+'회 / 시도 '+(r.counterAttempts||0)+'회 · 성공률 '+(r.counterRate||0)+'% · 회피 '+(r.evades||0)+'회 · 회피 반격 '+(r.evadeRetaliations||0)+'회 · 파괴 '+r.breaks+'개 · 빗나감 '+(r.whiffs||0)+'회 · 쓰러짐 '+(r.deaths||0)+'회'+(r.lastFailure?' · 마지막 피격/실패: '+r.lastFailure:'');}
 function dungeonBrief(){const level=$('dungeon').value,L=window.TW_LEVELS[level],A=window.TW_DUNGEONS.ARENAS[L.arena],q=data?.quests.find(q=>q.level===level);briefing.textContent=(q?.brief||'허수아비 훈련부터 시작하세요.')+' 기본 보상: '+fmt(A.rewards.gold)+' G · '+loot(A.rewards.items)+(data&&!data.unlocked.includes(level)?' · 이전 의뢰 보수 수령 필요':'');}
 let previousRoom='';
 function roomChanged(){const room=api.getRoom();const key=room?room.code+':'+room.leader+':'+room.members.map(m=>m.id).join(',')+':'+!!room.raid:'';if(key!==previousRoom){previousRoom=key;roomTools.replaceChildren();if(room&&!room.raid){if(room.leader===profile?.id){const list=select('파티장 위임',room.members.filter(m=>m.id!==profile.id&&m.connected).map(m=>[m.id,m.name]));roomTools.append(list.wrap,button('위임',()=>send('partyTransfer',{target:list.input.value}),!list.input.value));const why=select('모집 목적',[['first','첫 클리어'],['practice','연습'],['repeat','반복 토벌']],room.purpose);roomTools.append(why.wrap,button('목적 변경',()=>send('partyPurpose',{purpose:why.input.value})));}roomTools.append(button('동료 초대',()=>open('social')));}if(room?.raid){dialog.close();invitationDialog.close();}}
  const p=room?.raid?.players.find(p=>p.id===profile?.id);if(p){for(let slot=0;slot<2;slot++){const id=p.quickslots[slot],b=$('quick-item-'+slot);b.textContent=name(id)+' '+(profile.items[id]||0)+'개 · '+Math.max(0,3-(p.uses[id]||0))+'회'+(p.itemCd>0?' · '+Math.ceil(p.itemCd)+'초':'');b.disabled=p.itemCd>0||p.hp<=0||!(profile.items[id]>0)||(p.uses[id]||0)>=3;}feedback.textContent=(p.bleedT>0?'출혈 '+Math.ceil(p.bleedT)+'초 · ':'')+(p.lastFailure||'');if(['clear','wiped'].includes(room.raid.state)){let rec=$('rpg-result-record');if(!rec){rec=el('p');rec.id='rpg-result-record';$('scoreboard').after(rec);}rec.textContent=recordText({...p,counterRate:p.counterAttempts?Math.round(p.counters/p.counterAttempts*100):0});}}
 }
 function showCredentials(msg){api.saveToken(msg.token);if(msg.recoveryCode){secretCode.textContent=msg.recoveryCode;if(!secretDialog.open)secretDialog.showModal();}}
 function receive(msg){if(msg.type==='welcome'||msg.type==='profile'){profile=msg.profile;if(msg.type==='welcome'){data=null;admin=null;if(msg.recoveryCode)showCredentials(msg);if(tab==='recover')dialog.close();}if(dialog.open)render();}
  if(msg.type==='rpg'){data=msg.data;guild=data.guild;for(const o of $('dungeon').options)o.disabled=!data.unlocked.includes(o.value);dungeonBrief();if(dialog.open)render();}
  if(msg.type==='credentials')showCredentials(msg);
  if(msg.type==='rpgNotice')info(msg.text);
  if(msg.type==='rpgResult'){const r=msg.result;info(msg.action==='enhance'?(r.success?'강화 성공':'강화 실패')+' · +'+r.enh+' · 내구도 '+r.dur:msg.action==='quest'&&r.status==='claimed'?'의뢰 보수를 받았습니다.':'처리했습니다.');}
  if(msg.type==='error')info(msg.message);
  if(msg.type==='adminState'){admin=msg;if(dialog.open&&tab==='admin')render();}
  if(msg.type==='partyInvitation'){invitationDialog.replaceChildren(el('h2','파티 초대'),el('p',msg.name+' · '+window.TW_LEVELS[msg.level].name),button('수락',()=>{send('partyAccept',{token:msg.token});invitationDialog.close();}),button('거절',()=>invitationDialog.close()));if(!invitationDialog.open)invitationDialog.showModal();}
  if(msg.type==='loggedOut'){profile=data=admin=null;dialog.close();secretDialog.close();secretCode.textContent='';invitationDialog.close();}
 }
 return {receive,roomChanged,settings,open,isModal:()=>!!document.querySelector('dialog[open]'),brief:dungeonBrief};
}
