import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';

const html = fs.readFileSync(new URL('../game3d.html', import.meta.url), 'utf8');

test('cinematic HUD skin is enabled on game3d body', () => {
  assert.match(html, /<body class="cinema-hud-v1"/);
  assert.match(html, /CINEMATIC COMBAT HUD v01/);
});

test('combat system DOM contracts stay intact', () => {
  for (const id of [
    'game3d','bosshp','b-name','b-hp','b-stag','b-ph','bttimer','b-timer',
    'btparty','combo','combo-n','guide','vitals','v-hp','v-hpv','v-st','v-stv',
    'v-ult','v-ultv','stick','actions','counter','status'
  ]) assert.match(html, new RegExp(`id="${id}"`), `missing #${id}`);
});

test('cinematic layout covers player, boss, combo and action hierarchy', () => {
  for (const selector of [
    '.cinema-hud-v1 .btparty',
    '.cinema-hud-v1 .vitals',
    '.cinema-hud-v1 .bosshp',
    '.cinema-hud-v1 .combo',
    '.cinema-hud-v1 .actions',
    '.cinema-hud-v1 .abtn--atk',
    '.cinema-hud-v1 .guide'
  ]) assert.ok(html.includes(selector), `missing ${selector}`);
});

test('input controls are still generated by game3d.js, not replaced by fake HUD buttons', () => {
  const js = fs.readFileSync(new URL('../js/game3d.js', import.meta.url), 'utf8');
  assert.match(js, /el\.actions\.innerHTML=SK\.map/);
  for (const key of ['data-skill','data-dodge','data-guard','data-atk','data-ult'])
    assert.ok(js.includes(key), `missing ${key}`);
});
