/* 클레이브 셔터 부위파괴 — 서버 비공개 내구도 + 큰 실루엣 파괴 계약. */
const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),path=require('node:path');
const ROOT=path.join(__dirname,'..'),C=require('../server/field-boss-combat.cjs');
const boss=()=>{const o={id:'clave',x:0,z:0,max:1200000,hp:1200000,alive:true};C.setup(o,1000);return o;};
test('셔터 내구도는 서버 내부, 공개는 0/1/2 상태뿐이다',()=>{const o=boss(),v=C.view(o);assert.equal(o.shutterMax,96000);assert.equal(v.part,0);assert.equal('shutterHp' in v,false);assert.equal('shutterMax' in v,false);});
test('아인과 반격은 부위파괴 효율이 더 높다',()=>{const a=boss(),k=boss(),c=boss();const left={x:2,z:0},right={x:-2,z:0};C.damageShutter(a,left,{character:'ain'},10000,false,1200);C.damageShutter(k,left,{character:'kain'},10000,false,1200);C.damageShutter(c,right,{character:'ain'},10000,true,1200);assert.ok(a.shutterHp<k.shutterHp);assert.ok(c.shutterHp<a.shutterHp);});
test('왼손 셔터 쪽을 공략하면 반대쪽보다 부위 피해가 크게 들어간다',()=>{const l=boss(),r=boss(),lp={x:2,z:0},rp={x:-2,z:0};C.damageShutter(l,lp,{character:'kain'},10000,false,1200);C.damageShutter(r,rp,{character:'kain'},10000,false,1200);assert.ok(l.shutterHp<r.shutterHp);assert.equal(C.shutterExposure(l,rp,true),1,'반격은 위치와 무관하게 셔터에 꽂힌다');});
test('파괴 순간 경직하고 직선 셔터 돌진 후보가 사라진다',()=>{const o=boss(),p={id:'p',x:0,z:4};let r;while(o.shutterState<2)r=C.damageShutter(o,p,{character:'ain'},7000,true,1500);assert.equal(r.broken,true);assert.equal(o.combat.state,'stagger');const w=C.skillWeights(o,p);assert.equal(w.shutter,0);assert.ok(w.storm>0||w.slam>0);});
test('자산 파이프라인과 웹 화면은 분리 셔터 메시와 파괴 피드백을 가진다',()=>{const rig=fs.readFileSync(path.join(ROOT,'tools','3d','rig_boss_template.py'),'utf8'),motion=fs.readFileSync(path.join(ROOT,'js','mmo','boss-motion.js'),'utf8'),html=fs.readFileSync(path.join(ROOT,'mmo.html'),'utf8');assert.match(rig,/Boss_HeldPart/);assert.match(rig,/mesh\.separate\(type='SELECTED'\)/);assert.match(motion,/getObjectByName\('Boss_HeldPart'\)/);assert.match(motion,/brokenShutterGeometry/);assert.match(motion,/isolateHeldMaterial/);assert.match(motion,/tintHeldPart/);assert.match(motion,/emissiveIntensity/);assert.match(motion,/Number\.isInteger\(a\.part\)/);assert.match(html,/bossPartBreak/);const pipe=fs.readFileSync(path.join(ROOT,'tools','3d','part1_boss_pipeline.py'),'utf8');assert.match(pipe,/DESIGNED_TAKES/);assert.match(pipe,/clave_shut,clave_storm/);assert.match(pipe,/HW_RIG_TAKES/);const sc=fs.readFileSync(path.join(ROOT,'tools','2d','clave-shutter-break-scenario.mjs'),'utf8');assert.match(sc,/03-broken-impact/);assert.match(sc,/Boss_HeldPart 반쪽 geometry 계약/);});
