const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),os=require('node:os'),path=require('node:path'),{Store}=require('../server/store.cjs');
const password='Good-test-password-2026';
function memory(t){const s=new Store(null);t.after(()=>s.close());return s;}
test('guest upgrades to account, name/gear/rewards persist and password login rotates session key',async t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tw-account-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));let s=new Store(dir);const guest=s.guest('방문자');s.chooseName(guest.profile.id,'밤의아인');s.award('first',[guest.profile.id],'tutorial',{gold:5000,items:[['m_alloy',5]]});s.purchase(guest.profile.id,'a_hood',1);s.equip(guest.profile.id,'a_hood');const account=await s.register('Ain_User',password,'ignored',guest.profile.id);assert.equal(account.profile.id,guest.profile.id);assert.equal(account.profile.name,'밤의아인');assert.equal(account.profile.stats.hp,25050);assert.equal(account.profile.account,'ain_user');assert.throws(()=>s.login(guest.token));const guild=s.createGuild(guest.profile.id,'저장되는쉘터');s.close();s=new Store(dir);t.after(()=>s.close());const restored=await s.authenticate('AIN_USER',password);assert.equal(s.guild(restored.profile.id).id,guild.id);assert.equal(restored.profile.gold,3800);assert.equal(restored.profile.items.m_alloy,5);assert.equal(restored.profile.equipment.head,'a_hood');assert.equal(restored.profile.characterCreated,true);assert.throws(()=>s.login(account.token));await assert.rejects(s.authenticate('ain_user','wrong-password-test'));assert.ok(!JSON.stringify(restored.profile).includes(password));s.revoke(restored.profile.id);assert.throws(()=>s.login(restored.token));
});
test('character names are required, normalized, globally unique, immutable and validated',t=>{
 const s=memory(t),a=s.guest(),b=s.guest();assert.equal(a.profile.characterCreated,false);s.chooseName(a.profile.id,'Ａｉｎ');assert.equal(s.public(a.profile.id).name,'Ain');assert.throws(()=>s.chooseName(b.profile.id,'ain'),/이미/);for(const n of ['a','<script>','이름 공백','a'.repeat(17)])assert.throws(()=>s.chooseName(b.profile.id,n));assert.throws(()=>s.chooseName(a.profile.id,'다른이름'));s.chooseName(b.profile.id,'새벽_낫');
});
test('concurrent registration of the same account commits exactly one identity',async t=>{
 const s=memory(t);const results=await Promise.allSettled([s.register('same_name',password,'A'),s.register('SAME_NAME',password,'B')]);assert.equal(results.filter(r=>r.status==='fulfilled').length,1);assert.equal(s.db.prepare('SELECT count(*) AS n FROM profiles').get().n,1);
});
test('legacy JSON migration preserves guest keys and receipts without duplicate rewards',t=>{
 const dir=fs.mkdtempSync(path.join(os.tmpdir(),'tw-migrate-'));t.after(()=>fs.rmSync(dir,{recursive:true,force:true}));const crypto=require('node:crypto'),token='legacy-token';fs.writeFileSync(path.join(dir,'profiles.json'),JSON.stringify({version:1,profiles:{old:{id:'old',name:'옛아인',tokenHash:crypto.createHash('sha256').update(token).digest('hex'),gold:100,xp:600,items:{m_core:2},clears:{tutorial:1},receipts:['paid']}}}));const s=new Store(dir);t.after(()=>s.close());assert.equal(s.login(token).profile.gold,100);s.award('paid',['old'],'tutorial',{gold:500,items:[]});assert.equal(s.public('old').gold,100);assert.ok(fs.existsSync(path.join(dir,'profiles.json')));
});
test('guild membership persists, blocks multi-guild joining and transfers leader on departure',t=>{
 const s=memory(t),a=s.guest(),b=s.guest(),c=s.guest();const g=s.createGuild(a.profile.id,'새벽의 쉘터');s.joinGuild(b.profile.id,g.code);assert.equal(s.guild(b.profile.id).id,g.id);assert.throws(()=>s.createGuild(b.profile.id,'이중가입'));assert.throws(()=>s.joinGuild(c.profile.id,'bad'));s.leaveGuild(a.profile.id);assert.equal(s.guild(b.profile.id).owner,b.profile.id);assert.equal(s.guild(a.profile.id),null);s.leaveGuild(b.profile.id);assert.equal(s.db.prepare('SELECT count(*) AS n FROM guilds').get().n,0);
});
test('listing escrow, purchase and cancellation conserve currency/items; duplicate purchase fails',t=>{
 const s=memory(t),a=s.guest().profile.id,b=s.guest().profile.id,c=s.guest().profile.id;s.award('seed',[a,b,c],'tutorial',{gold:1000,items:[['m_core',10]]});const l=s.list(a,'m_core',4,100);assert.equal(s.public(a).items.m_core,6);assert.throws(()=>s.cancel(b,l.id));s.buy(b,l.id);assert.equal(s.public(a).gold,1400);assert.equal(s.public(b).gold,600);assert.equal(s.public(b).items.m_core,14);assert.throws(()=>s.buy(c,l.id));const back=s.list(a,'m_core',2,50);s.cancel(a,back.id);assert.equal(s.public(a).items.m_core,6);assert.throws(()=>s.list(a,'m_core',-1,10));assert.throws(()=>s.list(a,'m_core',2,0));assert.throws(()=>s.list(a,'q_record',1,10));assert.throws(()=>s.list(a,'m_core',7,10));
});
test('failed trade transaction rolls back escrow, currency, inventory and audit log',t=>{
 const s=memory(t),a=s.guest().profile.id,b=s.guest().profile.id;s.award('seed',[a,b],'tutorial',{gold:1000,items:[['m_core',10]]});const l=s.list(a,'m_core',4,100);s.save=()=>{throw Error('simulated disk failure');};assert.throws(()=>s.buy(b,l.id));assert.equal(s.public(a).gold,1000);assert.equal(s.public(b).gold,1000);assert.equal(s.public(b).items.m_core,10);assert.equal(s.market().length,1);assert.equal(s.db.prepare('SELECT count(*) AS n FROM trades').get().n,0);
});
