const SK=require('./rpg-skills.cjs'),crypto=require('node:crypto'),fs=require('node:fs'),path=require('node:path');
const {promisify}=require('node:util'),{backup}=require('node:sqlite');
const scrypt=promisify(crypto.scrypt),C=require('./content.cjs'),R=require('./rpg-rules.cjs');
const hash=v=>crypto.createHash('sha256').update(v).digest('hex');
const text=(v,max)=>{if(typeof v!=='string'||!v.trim()||v.length>max||/[<>\u0000-\u001f]/.test(v))throw Error('입력 내용을 확인하세요.');return v.normalize('NFKC').trim();};
const quantity=n=>{if(!Number.isSafeInteger(n)||n<1||n>999)throw Error('수량은 1–999 사이의 정수입니다.');return n;};
const password=p=>{if(typeof p!=='string'||p.length<10||Buffer.byteLength(p)>128)throw Error('비밀번호는 10자 이상, 128바이트 이하입니다.');};
const methods={
 initRpg(){this.db.exec(`
 CREATE TABLE IF NOT EXISTS recovery(player TEXT PRIMARY KEY REFERENCES profiles(id),hash TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS relationships(owner TEXT NOT NULL REFERENCES profiles(id),target TEXT NOT NULL REFERENCES profiles(id),kind TEXT NOT NULL,PRIMARY KEY(owner,target,kind));
 CREATE TABLE IF NOT EXISTS guild_settings(guild TEXT PRIMARY KEY REFERENCES guilds(id) ON DELETE CASCADE,notice TEXT NOT NULL DEFAULT '');
 CREATE TABLE IF NOT EXISTS guild_roles(player TEXT PRIMARY KEY REFERENCES profiles(id),guild TEXT NOT NULL,role TEXT NOT NULL);
 CREATE TABLE IF NOT EXISTS reports(id INTEGER PRIMARY KEY,reporter TEXT NOT NULL,target TEXT NOT NULL,reason TEXT NOT NULL,evidence TEXT NOT NULL,created INTEGER NOT NULL,status TEXT NOT NULL DEFAULT 'open');
 CREATE TABLE IF NOT EXISTS sanctions(player TEXT PRIMARY KEY,ban_until INTEGER NOT NULL DEFAULT 0,mute_until INTEGER NOT NULL DEFAULT 0,reason TEXT NOT NULL DEFAULT '');
 CREATE TABLE IF NOT EXISTS audit(id INTEGER PRIMARY KEY,actor TEXT NOT NULL,action TEXT NOT NULL,target TEXT NOT NULL,detail TEXT NOT NULL,created INTEGER NOT NULL);
 CREATE TABLE IF NOT EXISTS reward_mail(run TEXT NOT NULL,player TEXT NOT NULL,arena TEXT NOT NULL,reward TEXT NOT NULL,delivered INTEGER NOT NULL DEFAULT 0,created INTEGER NOT NULL,PRIMARY KEY(run,player));
 CREATE TABLE IF NOT EXISTS expeditions(id TEXT PRIMARY KEY,level TEXT NOT NULL,members TEXT NOT NULL,state TEXT NOT NULL,created INTEGER NOT NULL);
 `);this.statement("UPDATE expeditions SET state='interrupted' WHERE state='active'").run();this.deliverRewards();},
 audit(actor,action,target,detail={}){this.statement('INSERT INTO audit(actor,action,target,detail,created) VALUES(?,?,?,?,?)').run(actor,action,target,JSON.stringify(detail),Date.now());},
 mutate(id,action,fn){return this.transaction(()=>{const p=this.get(id),result=fn(p);this.put(p);this.audit(id,action,id,result||{});return {profile:this.public(id),result};});},
 debit(p,mats,gold=0){if(!Number.isSafeInteger(gold)||gold<0||p.gold<gold)throw Error('골드가 부족합니다.');const merged={};for(const [item,n]of mats){quantity(n);merged[item]=(merged[item]||0)+n;}for(const [item,n]of Object.entries(merged))if(!(p.items[item]>=n))throw Error((R.byId[item]?.name||item)+' 재료가 부족합니다.');p.gold-=gold;for(const [item,n]of Object.entries(merged))p.items[item]-=n;},
 addItems(p,items){for(const [id,n]of items){const item=R.byId[id];if(!item)continue;if(item.stats){if((p.items[id]||0)+(p.vault[id]||0)>0){p.items.m_alloy=(p.items.m_alloy||0)+3*n;}else {p.items[id]=1;if(n>1)p.items.m_alloy=(p.items.m_alloy||0)+3*(n-1);}}else p.items[id]=(p.items[id]||0)+n;}},
 gearInfo(p,id){const item=R.byId[id];if(!item?.stats)return null;const meta=p.gear[id]||{enh:id==='w_marsh_scythe'?5:0,dur:100};return {...meta,level:R.requirement(item)};},
 requireOwned(p,id){if(!R.byId[id]||!(p.items[id]>0))throw Error('보유하지 않은 물품입니다.');return R.byId[id];},
 requireDisposable(p,id){const item=this.requireOwned(p,id);if(p.locks[id]||Object.values(p.equipment).includes(id))throw Error('잠금 또는 착용 중인 장비입니다.');if(item.type==='quest')throw Error('의뢰 물품은 처분할 수 없습니다.');return item;},
 inventoryAction(id,op,item,n=1){quantity(n);return this.mutate(id,op,p=>{const definition=R.byId[item];if(!definition)throw Error('물품을 확인하세요.');
  if(op==='withdraw'){if(!(p.vault[item]>=n))throw Error('보관 수량이 부족합니다.');p.vault[item]-=n;p.items[item]=(p.items[item]||0)+n;return {item,quantity:n};}
  this.requireOwned(p,item);if(op==='lock'){if(!definition.stats)throw Error('장비만 잠글 수 있습니다.');p.locks[item]=!p.locks[item];return {item,locked:p.locks[item]};}
  if(op==='unequip'){if(definition.slot==='main')throw Error('주무기는 항상 착용해야 합니다.');if(p.equipment[definition.slot]===item)delete p.equipment[definition.slot];return {item};}
  this.requireDisposable(p,item);if(!(p.items[item]>=n))throw Error('수량이 부족합니다.');
  if(op==='deposit'){p.items[item]-=n;p.vault[item]=(p.vault[item]||0)+n;return {item,quantity:n};}
  if(op==='dismantle'){if(!definition.stats||n!==1)throw Error('장비를 하나 선택하세요.');p.items[item]--;const mats=(R.salvage[definition.rarity]||R.salvage.common).map(([key,count])=>[key,Math.max(1,Math.round(count*(.6+.4*this.gearInfo(p,item).dur/100)))]);delete p.gear[item];this.addItems(p,mats);return {item,items:mats};}
  if(op==='vendorSell'){const unit=C.shop.find(s=>s.id===item)?.sell||(definition.stats?Math.floor(definition.price*.2):0);if(!unit)throw Error('판매할 수 없는 물품입니다.');p.items[item]-=n;p.gold+=unit*n;if(definition.stats)delete p.gear[item];return {item,gold:unit*n};}
  throw Error('지원하지 않는 가방 요청입니다.');});},
 craft(id,recipe){const r=R.recipes.find(r=>r.id===recipe);if(!r)throw Error('제작법을 확인하세요.');return this.mutate(id,'craft',p=>{if(1+Math.floor(p.xp/1200)<r.level)throw Error('제작 요구 레벨이 부족합니다.');if(R.byId[r.result].stats&&((p.items[r.result]||0)+(p.vault[r.result]||0)>0))throw Error('이미 보유한 장비입니다.');this.debit(p,r.mats,r.cost);this.addItems(p,[[r.result,r.yield||1]]);return {item:r.result,quantity:r.yield||1};});},
 enhanceQuote(p,item){const meta=this.gearInfo(p,item);if(!meta)return null;const step=C.enhance.find(s=>s.to===meta.enh+1);if(!step)return null;return {...step,mats:step.mats.filter(([id])=>id!=='m_booster'),rate:Math.min(90,step.rate+(p.failstack||0)),booster:step.mats.find(([id])=>id==='m_booster')?.[1]||1,drop:step.to<=6?1:2,durLoss:6+step.to*2};},
 enhance(id,item,protect){return this.mutate(id,'enhance',p=>{const definition=this.requireOwned(p,item);if(!definition.stats)throw Error('장비를 선택하세요.');const meta=this.gearInfo(p,item),q=this.enhanceQuote(p,item);if(!q)throw Error('최대 강화 단계입니다.');if(meta.dur<20)throw Error('내구도 20 미만입니다. 먼저 수리하세요.');this.debit(p,[...q.mats,...(protect?[['m_booster',q.booster]]:[])],q.cost);const success=crypto.randomInt(100000)<q.rate*1000;if(success){meta.enh=q.to;meta.dur=Math.max(0,meta.dur-2);p.failstack=0;}else{p.failstack=Math.min(30,(p.failstack||0)+3);meta.dur=Math.max(0,meta.dur-q.durLoss);if(!protect)meta.enh=Math.max(0,meta.enh-q.drop);}p.gear[item]=meta;return {item,success,enh:meta.enh,dur:meta.dur,protected:!!protect,rate:q.rate};});},
 repair(id,item){return this.mutate(id,'repair',p=>{const d=this.requireOwned(p,item),m=this.gearInfo(p,item);if(!m||m.dur===100)throw Error('수리할 장비가 없습니다.');const cost=Math.max(100,Math.round(d.price*.15*(100-m.dur)/100));this.debit(p,[],cost);m.dur=100;p.gear[item]=m;return {item,cost};});},
 skillUp(id,skill){return this.mutate(id,'skillUp',p=>SK.up(p,skill));},
 skillBranch(id,skill,br){return this.mutate(id,'skillBranch',p=>SK.branch(p,skill,br));},
 skillReset(id){return this.mutate(id,'skillReset',p=>SK.reset(p));},
 skillsFor(id){return SK.resolve(this.get(id));},
 trait(id,trait){if(!Object.hasOwn(R.traits,trait))throw Error('특성을 선택하세요.');return this.mutate(id,'trait',p=>{p.trait=trait;return {trait};});},
 questState(id){const p=this.get(id);return R.quests.map(q=>({...q,status:p.quests[q.id]==='claimed'?'claimed':q.previous&&p.quests[q.previous]!=='claimed'?'locked':p.quests[q.id]==='accepted'?(p.clears[q.arena]>0?'complete':'active'):'available'}));},
 questAction(id,quest,op){const q=this.questState(id).find(q=>q.id===quest);if(!q)throw Error('의뢰를 확인하세요.');return this.mutate(id,'quest',p=>{if(op==='accept'&&q.status==='available'){p.quests[q.id]='accepted';return {quest,status:'accepted'};}if(op==='claim'&&q.status==='complete'){p.quests[q.id]='claimed';p.gold+=q.gold;p.xp+=q.xp;this.addItems(p,q.items);return {quest,status:'claimed',gold:q.gold,xp:q.xp,items:q.items};}throw Error('의뢰 조건을 확인하세요.');});},
 canEnter(id,level){const q=R.quests.find(q=>q.level===level);if(!q)return false;const p=this.get(id);return !q.previous||p.quests[q.previous]==='claimed'||p.clears[q.arena]>0;},
 supplies(id,slots){if(!Array.isArray(slots)||slots.length!==2||slots.some(i=>!['c_potion','c_antidote','c_throw'].includes(i)))throw Error('소모품 두 칸을 선택하세요.');return this.mutate(id,'quickslots',p=>{p.quickslots=slots;return {slots};});},
 consume(id,item){return this.mutate(id,'consume',p=>{this.debit(p,[[item,1]]);return {item};});},
 startRun(run,level,ids){this.transaction(()=>this.statement('INSERT INTO expeditions VALUES(?,?,?,?,?)').run(run,level,JSON.stringify(ids),'active',Date.now()));},
 queueRewards(run,ids,arena,reward){this.transaction(()=>{for(const id of new Set(ids)){const p=this.get(id);const first=!p.clears[arena];const personal=reward.players?.find(x=>x.id===id);const grant={...reward,first,firstGold:first?1000:0,bonusItems:[...(first?[['m_booster',2],['m_heart',1]]:[]),...(reward.breaksTotal?[['m_bone',reward.breaksTotal]]:[])],record:personal||null};delete grant.players;this.statement('INSERT OR IGNORE INTO reward_mail VALUES(?,?,?,?,0,?)').run(run,id,arena,JSON.stringify(grant),Date.now());}this.statement("UPDATE expeditions SET state='clear' WHERE id=?").run(run);});return this.deliverRewards();},
 deliverRewards(id){const rows=id?this.statement('SELECT * FROM reward_mail WHERE delivered=0 AND player=?').all(id):this.statement('SELECT * FROM reward_mail WHERE delivered=0').all();const changed={};for(const row of rows)this.transaction(()=>{if(this.statement('SELECT delivered FROM reward_mail WHERE run=? AND player=?').get(row.run,row.player).delivered)return;const reward=JSON.parse(row.reward),p=this.get(row.player);if(!this.statement('SELECT 1 FROM receipts WHERE run=? AND player=?').get(row.run,row.player)){reward.first=!p.clears[row.arena];reward.firstGold=reward.first?1000:0;reward.bonusItems=[...(reward.first?[['m_booster',2],['m_heart',1]]:[]),...(reward.breaksTotal?[['m_bone',reward.breaksTotal]]:[])];p.gold+=reward.gold+(reward.firstGold||0);p.xp+=600;p.clears[row.arena]=(p.clears[row.arena]||0)+1;this.addItems(p,[...reward.items,...(reward.bonusItems||[])]);this.put(p);this.statement('INSERT INTO receipts VALUES(?,?)').run(row.run,row.player);}this.statement('UPDATE reward_mail SET delivered=1,reward=? WHERE run=? AND player=?').run(JSON.stringify(reward),row.run,row.player);this.audit(row.player,'reward',row.run,{arena:row.arena,gold:reward.gold});changed[row.player]=this.public(row.player);});return changed;},
 rewardHistory(id){return this.statement('SELECT * FROM reward_mail WHERE player=? ORDER BY created DESC LIMIT 30').all(id).map(r=>({...r,reward:JSON.parse(r.reward)}));},
 playerNamed(name){const r=this.statement('SELECT player FROM character_names WHERE name_key=?').get(text(name,16).toLowerCase());if(!r)throw Error('캐릭터를 찾을 수 없습니다.');return r.player;},
 blocked(a,b){this.blockCache??=new Map();if(!this.blockCache.has(a))this.blockCache.set(a,new Set(this.statement("SELECT target FROM relationships WHERE owner=? AND kind='block'").all(a).map(r=>r.target)));return this.blockCache.get(a).has(b);},
 relationship(id,target,action){if(id===target)throw Error('자신을 대상으로 할 수 없습니다.');this.row(target);return this.transaction(()=>{if(action==='block'){if(!this.blocked(id,target)&&this.statement("SELECT count(*) n FROM relationships WHERE owner=? AND kind='block'").get(id).n>=200)throw Error('차단 목록은 200명까지입니다.');this.statement("DELETE FROM relationships WHERE ((owner=? AND target=?) OR (owner=? AND target=?)) AND kind!='block'").run(id,target,target,id);this.statement("INSERT OR IGNORE INTO relationships VALUES(?,?,'block')").run(id,target);}else if(action==='unblock')this.statement("DELETE FROM relationships WHERE owner=? AND target=? AND kind='block'").run(id,target);else if(action==='remove'){this.statement("DELETE FROM relationships WHERE ((owner=? AND target=?) OR (owner=? AND target=?)) AND kind!='block'").run(id,target,target,id);}else {if(this.blocked(id,target)||this.blocked(target,id))throw Error('이 요청을 보낼 수 없습니다.');if(action==='request'){if(this.statement("SELECT count(*) n FROM relationships WHERE (owner=? OR target=?) AND kind!='block'").get(id,id).n>=100||this.statement("SELECT count(*) n FROM relationships WHERE (owner=? OR target=?) AND kind!='block'").get(target,target).n>=100)throw Error('친구 요청 한도입니다.');if(!this.statement("SELECT 1 FROM relationships WHERE owner=? AND target=? AND kind='friend'").get(id,target))this.statement("INSERT OR IGNORE INTO relationships VALUES(?,?,'request')").run(id,target);}else if(action==='accept'){if(!this.statement("SELECT 1 FROM relationships WHERE owner=? AND target=? AND kind='request'").get(target,id))throw Error('받은 요청이 없습니다.');this.statement("DELETE FROM relationships WHERE ((owner=? AND target=?) OR (owner=? AND target=?)) AND kind='request'").run(id,target,target,id);for(const [a,b]of [[id,target],[target,id]])this.statement("INSERT OR IGNORE INTO relationships VALUES(?,?,'friend')").run(a,b);}else throw Error('친구 요청을 확인하세요.');}this.audit(id,action,target);this.blockCache?.delete(id);this.blockCache?.delete(target);});},
 contacts(id){return this.statement('SELECT * FROM relationships WHERE owner=? OR target=?').all(id,id).filter(r=>r.owner===id||r.kind==='request').map(r=>({id:r.owner===id?r.target:r.owner,name:this.get(r.owner===id?r.target:r.owner).name,kind:r.kind,incoming:r.owner!==id}));},
 guildManage(id,action,target,value){return this.transaction(()=>{const g=this.guild(id);if(!g)throw Error('가입한 길드가 없습니다.');const officer=this.statement("SELECT 1 FROM guild_roles WHERE player=? AND guild=? AND role='officer'").get(id,g.id);if(g.owner!==id&&!officer)throw Error('길드 관리 권한이 없습니다.');if(action==='notice'){const notice=value===''?'':text(value,240);this.statement('INSERT INTO guild_settings VALUES(?,?) ON CONFLICT(guild) DO UPDATE SET notice=excluded.notice').run(g.id,notice);}else {if(target===id||!g.members.some(m=>m.id===target))throw Error('길드원을 선택하세요.');const targetOfficer=this.statement('SELECT 1 FROM guild_roles WHERE player=? AND guild=?').get(target,g.id);if(action==='kick'){if(target===g.owner||officer&&targetOfficer)throw Error('해당 길드원을 추방할 수 없습니다.');this.statement('DELETE FROM guild_members WHERE player=?').run(target);this.statement('DELETE FROM guild_roles WHERE player=?').run(target);}else {if(g.owner!==id)throw Error('길드장만 실행할 수 있습니다.');if(action==='transfer'){this.statement('UPDATE guilds SET owner=? WHERE id=?').run(target,g.id);this.statement('DELETE FROM guild_roles WHERE player IN (?,?)').run(id,target);}else if(action==='officer')this.statement("INSERT INTO guild_roles VALUES(?,?,'officer') ON CONFLICT(player) DO UPDATE SET guild=excluded.guild,role=excluded.role").run(target,g.id);else if(action==='member')this.statement('DELETE FROM guild_roles WHERE player=?').run(target);else throw Error('관리 요청을 확인하세요.');}}this.audit(id,'guild:'+action,target||g.id);});},
 guildDetails(id){const g=this.guild(id);if(!g)return null;const roles=this.statement('SELECT * FROM guild_roles WHERE guild=?').all(g.id);return {...g,notice:this.statement('SELECT notice FROM guild_settings WHERE guild=?').get(g.id)?.notice||'',members:g.members.map(m=>({...m,role:m.id===g.owner?'owner':roles.find(r=>r.player===m.id)?.role||'member'}))};},
 sanction(id){return this.statement('SELECT * FROM sanctions WHERE player=?').get(id)||{ban_until:0,mute_until:0};},
 checkBan(id){if(this.sanction(id).ban_until>Date.now())throw Error('이용이 제한된 계정입니다.');},
 report(id,target,reason,evidence=''){this.row(target);reason=text(reason,240);return this.transaction(()=>{if(this.statement('SELECT count(*) n FROM reports WHERE reporter=? AND created>?').get(id,Date.now()-3600000).n>=5)throw Error('신고는 시간당 5건까지 가능합니다.');this.statement('INSERT INTO reports(reporter,target,reason,evidence,created) VALUES(?,?,?,?,?)').run(id,target,reason,evidence.slice(0,1500),Date.now());return {reported:true};});},
 moderate(actor,action,target,minutes,reason){return this.transaction(()=>{if(action==='resolve'){this.statement("UPDATE reports SET status='resolved' WHERE id=?").run(quantity(Number(target)));}else {this.row(target);quantity(minutes);reason=text(reason,240);if(!['ban','mute','lift'].includes(action))throw Error('제재 종류를 확인하세요.');const old=this.sanction(target);this.statement('INSERT INTO sanctions VALUES(?,?,?,?) ON CONFLICT(player) DO UPDATE SET ban_until=excluded.ban_until,mute_until=excluded.mute_until,reason=excluded.reason').run(target,action==='lift'?0:action==='ban'?Date.now()+minutes*60000:old.ban_until,action==='lift'?0:action==='mute'?Date.now()+minutes*60000:old.mute_until,reason);}this.audit(actor,'moderate:'+action,String(target),{minutes,reason});});},
 async changePassword(id,current,next){password(next);const r=this.row(id);if(!r.username)throw Error('계정 등록이 필요합니다.');password(current);const digest=await scrypt(current,r.salt,64);if(!crypto.timingSafeEqual(digest,Buffer.from(r.digest,'hex')))throw Error('현재 비밀번호를 확인하세요.');const salt=crypto.randomBytes(16).toString('hex'),key=(await scrypt(next,salt,64)).toString('hex'),token=crypto.randomBytes(32).toString('base64url'),code=crypto.randomBytes(24).toString('base64url');this.transaction(()=>{if(this.row(id).digest!==r.digest)throw Error('계정 정보가 변경되었습니다. 다시 로그인하세요.');this.statement('UPDATE profiles SET salt=?,digest=?,token_hash=? WHERE id=?').run(salt,key,hash(token),id);this.statement('INSERT INTO recovery VALUES(?,?) ON CONFLICT(player) DO UPDATE SET hash=excluded.hash').run(id,hash(code));this.audit(id,'password-change',id);});return {token,recoveryCode:code};},
 async recover(username,code,next){password(next);if(typeof username!=='string'||!/^[a-zA-Z0-9_]{4,32}$/.test(username)||typeof code!=='string'||code.length>128)throw Error('복구 정보를 확인하세요.');const r=this.statement('SELECT p.*,r.hash recovery_hash FROM profiles p JOIN recovery r ON r.player=p.id WHERE p.username=?').get(username.toLowerCase());const valid=!!r&&crypto.timingSafeEqual(Buffer.from(hash(code),'hex'),Buffer.from(r.recovery_hash,'hex'));if(!valid)throw Error('복구 정보를 확인하세요.');this.checkBan(r.id);const salt=crypto.randomBytes(16).toString('hex'),digest=(await scrypt(next,salt,64)).toString('hex'),token=crypto.randomBytes(32).toString('base64url'),recoveryCode=crypto.randomBytes(24).toString('base64url');this.transaction(()=>{const live=this.statement('SELECT hash FROM recovery WHERE player=?').get(r.id);if(live?.hash!==r.recovery_hash||this.row(r.id).digest!==r.digest)throw Error('이미 사용된 복구 코드입니다.');this.statement('UPDATE profiles SET salt=?,digest=?,token_hash=? WHERE id=?').run(salt,digest,hash(token),r.id);this.statement('UPDATE recovery SET hash=? WHERE player=?').run(hash(recoveryCode),r.id);this.audit(r.id,'account-recovery',r.id);});return {profile:this.public(r.id),token,recoveryCode};},
 async backupData(directory){if(this.backupPending)throw Error('백업이 진행 중입니다.');this.backupPending=true;try{fs.mkdirSync(directory,{recursive:true,mode:0o700});const file=path.join(directory,'world-'+Date.now()+'.sqlite');await backup(this.db,file);fs.chmodSync(file,0o600);const files=fs.readdirSync(directory).filter(n=>/^world-\d+\.sqlite$/.test(n)).sort();for(const old of files.slice(0,-5))fs.unlinkSync(path.join(directory,old));return file;}finally{this.backupPending=false;}},
 rpgState(id){const p=this.get(id),equipment=C.equipment.filter(R.supported).map(item=>{const meta=this.gearInfo(p,item.id),candidate={...p,equipment:{...p.equipment,[item.slot]:item.id}};return {id:item.id,name:item.name,type:item.type,slot:item.slot,rarity:item.rarity,effect:item.effect.replace(/<[^>]*>/g,''),level:meta.level,enh:meta.enh,dur:meta.dur,repairCost:meta.dur===100?0:Math.max(100,Math.round(item.price*.15*(100-meta.dur)/100)),quote:this.enhanceQuote(p,item.id),comparison:this.stats(candidate)};});return {quests:this.questState(id),equipment,skills:SK.view(p),recipes:R.recipes,traits:R.traits,contacts:this.contacts(id),mail:this.rewardHistory(id),unlocked:Object.keys(C.levels).filter(l=>this.canEnter(id,l)),interrupted:this.statement("SELECT id,level,created FROM expeditions WHERE state='interrupted' AND EXISTS(SELECT 1 FROM json_each(members) WHERE value=?) ORDER BY created DESC LIMIT 5").all(id)};}
};
function install(Store){const normalize=Store.prototype.normalize,stats=Store.prototype.stats,equip=Store.prototype.equip,purchase=Store.prototype.purchase,leaveGuild=Store.prototype.leaveGuild,register=Store.prototype.register;
 Object.assign(Store.prototype,methods);
 Store.prototype.register=async function(...args){const result=await register.apply(this,args),code=crypto.randomBytes(24).toString('base64url');this.transaction(()=>this.statement('INSERT INTO recovery VALUES(?,?) ON CONFLICT(player) DO UPDATE SET hash=excluded.hash').run(result.profile.id,hash(code)));return {...result,recoveryCode:code};};
 Store.prototype.normalize=function(p){p=normalize.call(this,p);p={vault:{},locks:{},gear:{},quests:{},skills:{},trait:'balanced',quickslots:['c_potion','c_antidote'],failstack:0,...p};if(!p.rpgVersion){p.items={...p.items};for(const id of Object.values(p.equipment))if(id&&!p.items[id]&&!p.vault[id])p.items[id]=1;p.rpgVersion=1;}return p;};
 Store.prototype.stats=function(p){if(typeof p==='string')p=this.get(p);const result=stats.call(this,p);let hp=result.hp,defense=result.defense;for(const id of Object.values(p.equipment||{})){const item=R.byId[id];if(!item?.stats||item.type==='weapon')continue;const m=this.gearInfo(p,id),factor=(1+.04*m.enh)*(m.dur===0?.5:1);hp+=(item.stats.hp||0)*(factor-1);defense+=(item.stats.def||0)*(factor-1);}const main=p.equipment.main||'w_marsh_scythe',weapon=R.byId[main],meta=this.gearInfo(p,main);const base=C.equipment.find(i=>i.id==='w_marsh_scythe');const atkScale=weapon?(weapon.stats.atk+weapon.stats.atkEx)/(base.stats.atk+base.stats.atkEx)*(1+.04*meta.enh)/1.2*(meta.dur===0?.5:1):1;const trait=R.traits[p.trait]||R.traits.balanced,equipped=Object.values(p.equipment),sum=key=>equipped.reduce((n,id)=>n+(R.byId[id]?.stats?.[key]||0),0);const effects={critChance:Math.min(.5,(5+sum('crit'))/100),critDamage:1.5+sum('critDmg')/100,skillMult:1+sum('skill')/100,bleedChance:['w_marsh_scythe','w_rust_executioner'].includes(main)?.07:0,bleedDuration:main==='w_rust_executioner'?4:3,bleedMult:equipped.includes('acc_blood_ring')?1.1:1,statusDuration:equipped.includes('acc_charm')?.9:1,bleedResist:equipped.includes('a_reed_cuirass')?.08:0,moveMult:equipped.includes('a_black_greaves')?1.02:1,counterBuff:equipped.includes('a_steel_gauntlet'),evadeBuff:equipped.includes('a_ranger_boots')};return {...result,...effects,hp:Math.round(hp*(trait.hp||1)),defense:Math.round(defense),atk:Math.round(result.atk*atkScale),trait:p.trait,counterMult:trait.counter||1,partMult:trait.part||1};};
 Store.prototype.equip=function(id,item){const d=R.byId[item];if(!d?.stats||!R.supported(d))throw Error('아인이 착용할 수 없는 장비입니다.');if(this.public(id).level<R.requirement(d))throw Error('착용 요구 레벨이 부족합니다.');if(d.type==='weapon')return this.mutate(id,'equip',p=>{this.requireOwned(p,item);p.equipment.main=item;}).profile;return equip.call(this,id,item);};
 Store.prototype.shop=function(){return [...C.shop.filter(i=>i.buy&&!['c_tool'].includes(i.id)).map(i=>({id:i.id,price:i.buy})),...C.equipment.filter(i=>R.supported(i)).map(i=>({id:i.id,price:i.price}))];};
 Store.prototype.purchase=function(id,item,n){if(R.byId[item]?.stats){const p=this.get(id);if(n!==1||(p.items[item]||0)+(p.vault[item]||0)>0)throw Error('장비는 종류별 하나만 보유합니다.');}return purchase.call(this,id,item,n);};
 Store.prototype.leaveGuild=function(id){const result=leaveGuild.call(this,id);this.statement('DELETE FROM guild_roles WHERE player=?').run(id);return result;};
}
module.exports={install};
