const fs=require('node:fs'),path=require('node:path'),crypto=require('node:crypto');
const {promisify}=require('node:util'),{DatabaseSync}=require('node:sqlite'),C=require('./content.cjs');
const scrypt=promisify(crypto.scrypt),hash=t=>crypto.createHash('sha256').update(t).digest('hex');
const CHARACTERS=['ain','kain','ryu','sera'];
const START={ain:'w_marsh_scythe',kain:'w_kain_greatsword',ryu:'w_ryu_dagger',sera:'w_sera_flask'};
const cleanName=n=>(typeof n==='string'?n:'아인').replace(/[\u0000-\u001f\u007f<>]/g,'').trim().slice(0,16)||'아인';
const accountName=n=>{if(typeof n!=='string'||!/^[a-zA-Z0-9_]{4,32}$/.test(n))throw Error('계정 ID는 영문·숫자·밑줄 4–32자입니다.');return n.toLowerCase();};
function passwordCheck(p){if(typeof p!=='string'||p.length<10||Buffer.byteLength(p)>128)throw Error('비밀번호는 10자 이상, 128바이트 이하로 입력하세요.');}
function integer(n,max){if(!Number.isSafeInteger(n)||n<1||n>max)throw Error('수량 또는 가격을 확인하세요.');return n;}
class Store{
 constructor(directory){
  this.directory=directory;this.file=directory&&path.join(directory,'world.sqlite');if(directory)fs.mkdirSync(directory,{recursive:true,mode:0o700});
  this.db=new DatabaseSync(this.file||':memory:');if(this.file)fs.chmodSync(this.file,0o600);this.db.exec(`PRAGMA journal_mode=WAL; PRAGMA synchronous=FULL; PRAGMA foreign_keys=ON;
   CREATE TABLE IF NOT EXISTS meta(key TEXT PRIMARY KEY,value TEXT NOT NULL);
   CREATE TABLE IF NOT EXISTS profiles(id TEXT PRIMARY KEY,token_hash TEXT UNIQUE NOT NULL,username TEXT UNIQUE,salt TEXT,digest TEXT,data TEXT NOT NULL);
   CREATE TABLE IF NOT EXISTS receipts(run TEXT NOT NULL,player TEXT NOT NULL REFERENCES profiles(id),PRIMARY KEY(run,player));
   CREATE TABLE IF NOT EXISTS listings(id TEXT PRIMARY KEY,seller TEXT NOT NULL REFERENCES profiles(id),item TEXT NOT NULL,quantity INTEGER NOT NULL CHECK(quantity>0),price INTEGER NOT NULL CHECK(price>0),created INTEGER NOT NULL);
   CREATE TABLE IF NOT EXISTS character_names(name_key TEXT PRIMARY KEY,player TEXT UNIQUE NOT NULL REFERENCES profiles(id));
   CREATE TABLE IF NOT EXISTS guilds(id TEXT PRIMARY KEY,name TEXT NOT NULL,name_key TEXT UNIQUE NOT NULL,code TEXT UNIQUE NOT NULL,owner TEXT NOT NULL REFERENCES profiles(id));
   CREATE TABLE IF NOT EXISTS guild_members(player TEXT PRIMARY KEY REFERENCES profiles(id),guild TEXT NOT NULL REFERENCES guilds(id),joined INTEGER NOT NULL);
   CREATE TABLE IF NOT EXISTS trades(id INTEGER PRIMARY KEY,listing TEXT NOT NULL UNIQUE,buyer TEXT NOT NULL,seller TEXT NOT NULL,item TEXT NOT NULL,quantity INTEGER NOT NULL,total INTEGER NOT NULL,created INTEGER NOT NULL);`);
  if(!this.statement("SELECT value FROM meta WHERE key='legacyImported'").get())this.transaction(()=>{
   const legacy=directory&&path.join(directory,'profiles.json');if(legacy&&fs.existsSync(legacy)){
    const data=JSON.parse(fs.readFileSync(legacy,'utf8'));if(data.version!==1)throw Error('Unsupported legacy profile version');
    for(const p of Object.values(data.profiles)){const {tokenHash,receipts,...rest}=p;this.statement('INSERT OR IGNORE INTO profiles(id,token_hash,data) VALUES(?,?,?)').run(p.id,tokenHash,JSON.stringify(this.normalize(rest)));for(const run of receipts||[])this.statement('INSERT OR IGNORE INTO receipts VALUES(?,?)').run(run,p.id);}
   }this.statement('INSERT INTO meta VALUES(?,?)').run('legacyImported','1');
  });
  this.initRpg();
 }
 normalize(p){const character=CHARACTERS.includes(p&&p.character)?p.character:'ain';
  return {gold:0,xp:0,items:{},clears:{},...p,character,equipment:{main:START[character],...(p&&p.equipment)}};}
 transaction(fn){this.db.exec('BEGIN IMMEDIATE');try{const value=fn();this.save();this.db.exec('COMMIT');return value;}catch(e){this.db.exec('ROLLBACK');throw e;}}
 statement(sql){this.statements??=new Map();if(!this.statements.has(sql))this.statements.set(sql,this.db.prepare(sql));return this.statements.get(sql);}
 save(){} // Test seam for I/O failures; SQLite commits all writes atomically.
 row(id){const r=this.statement('SELECT * FROM profiles WHERE id=?').get(id);if(!r)throw Error('캐릭터를 찾을 수 없습니다.');return r;}
 get(id){return this.normalize(JSON.parse(this.row(id).data));}
 put(p){this.statement('UPDATE profiles SET data=? WHERE id=?').run(JSON.stringify(p),p.id);}
 public(id){const r=this.row(id),p=this.normalize(JSON.parse(r.data));return {...p,account:r.username,characterCreated:!!this.statement('SELECT 1 FROM character_names WHERE player=?').get(id),level:1+Math.floor(p.xp/1200),stats:this.stats(p)};}
 chooseName(id,name,character){if(typeof name!=='string')throw Error('캐릭터 이름을 입력하세요.');
  if(character!==undefined&&!CHARACTERS.includes(character))throw Error('사용할 캐릭터를 고르세요.');name=name.normalize('NFKC').trim();if(!/^[\p{L}\p{N}_]{2,16}$/u.test(name))throw Error('캐릭터 이름은 한글·영문·숫자·밑줄 2–16자입니다.');return this.transaction(()=>{if(this.statement('SELECT 1 FROM character_names WHERE player=?').get(id))throw Error('이미 캐릭터 이름을 정했습니다.');const key=name.toLowerCase();if(this.statement('SELECT 1 FROM character_names WHERE name_key=?').get(key))throw Error('이미 사용 중인 캐릭터 이름입니다.');this.statement('INSERT INTO character_names VALUES(?,?)').run(key,id);const p=this.get(id);p.name=name;
  if(character){p.character=character;p.equipment={...p.equipment,main:START[character]};p.items={...p.items};delete p.items[START.ain];p.items[START[character]]=1;}
  this.put(p);return this.public(id);});}
 guild(id){const guild=this.statement('SELECT g.* FROM guilds g JOIN guild_members m ON m.guild=g.id WHERE m.player=?').get(id);if(!guild)return null;return {...guild,members:this.statement("SELECT m.player AS id,json_extract(p.data,'$.name') AS name FROM guild_members m JOIN profiles p ON p.id=m.player WHERE m.guild=? ORDER BY m.joined,m.player").all(guild.id)};}
 createGuild(id,name){if(typeof name!=='string'||name.trim().length<2||name.trim().length>24||/[<>\u0000-\u001f]/.test(name))throw Error('길드 이름은 2–24자로 입력하세요.');name=name.normalize('NFKC').trim();return this.transaction(()=>{if(this.guild(id))throw Error('이미 길드에 가입되어 있습니다.');if(this.statement('SELECT 1 FROM guilds WHERE name_key=?').get(name.toLowerCase()))throw Error('이미 사용 중인 길드 이름입니다.');const guild=crypto.randomUUID();this.statement('INSERT INTO guilds VALUES(?,?,?,?,?)').run(guild,name,name.toLowerCase(),crypto.randomBytes(5).toString('hex').toUpperCase(),id);this.statement('INSERT INTO guild_members VALUES(?,?,?)').run(id,guild,Date.now());return this.guild(id);});}
 joinGuild(id,code){if(typeof code!=='string')throw Error('길드 초대 코드를 확인하세요.');return this.transaction(()=>{if(this.guild(id))throw Error('이미 길드에 가입되어 있습니다.');const g=this.statement('SELECT * FROM guilds WHERE code=?').get(code.trim().toUpperCase());if(!g)throw Error('길드를 찾을 수 없습니다.');if(this.statement('SELECT count(*) AS n FROM guild_members WHERE guild=?').get(g.id).n>=100)throw Error('길드가 가득 찼습니다.');this.statement('INSERT INTO guild_members VALUES(?,?,?)').run(id,g.id,Date.now());return this.guild(id);});}
 leaveGuild(id){return this.transaction(()=>{const guild=this.guild(id);if(!guild)throw Error('가입한 길드가 없습니다.');this.statement('DELETE FROM guild_members WHERE player=?').run(id);const next=this.statement('SELECT player FROM guild_members WHERE guild=? ORDER BY joined,player LIMIT 1').get(guild.id);if(!next)this.statement('DELETE FROM guilds WHERE id=?').run(guild.id);else if(guild.owner===id)this.statement('UPDATE guilds SET owner=? WHERE id=?').run(next.player,guild.id);return guild.id;});}
 stats(p){if(typeof p==='string')p=this.get(p);const level=1+Math.floor(p.xp/1200),base=(C.characters[p.character]||C.character).stats;let hp=base.hp+(level-1)*150,defense=0;for(const id of Object.values(p.equipment||{})){const item=C.equipment.find(i=>i.id===id);if(item&&item.type!=='weapon'){hp+=item.stats.hp||0;defense+=item.stats.def||0;}}return {hp,atk:base.atk+(level-1)*15,aspd:base.aspd,defense};}
 guest(name){const token=crypto.randomBytes(32).toString('base64url'),p=this.normalize({id:crypto.randomUUID(),name:cleanName(name)});this.transaction(()=>this.statement('INSERT INTO profiles(id,token_hash,data) VALUES(?,?,?)').run(p.id,hash(token),JSON.stringify(p)));return {profile:this.public(p.id),token};}
 login(token,name){if(!token)return this.guest(name);if(typeof token!=='string'||token.length>128)throw Error('저장된 접속 키가 유효하지 않습니다.');const row=this.statement('SELECT id FROM profiles WHERE token_hash=?').get(hash(token));if(!row)throw Error('저장된 접속 키가 유효하지 않습니다. 계정으로 로그인해 주세요.');return {profile:this.public(row.id),token};}
 async register(username,password,name,guestId){username=accountName(username);passwordCheck(password);if(this.statement('SELECT id FROM profiles WHERE username=?').get(username))throw Error('이미 사용 중인 계정 ID입니다.');if(guestId&&this.row(guestId).username)throw Error('이미 계정에 연결된 캐릭터입니다.');const salt=crypto.randomBytes(16).toString('hex'),digest=(await scrypt(password,salt,64)).toString('hex'),token=crypto.randomBytes(32).toString('base64url');
  const id=this.transaction(()=>{if(this.statement('SELECT id FROM profiles WHERE username=?').get(username))throw Error('이미 사용 중인 계정 ID입니다.');if(guestId){if(this.row(guestId).username)throw Error('이미 계정에 연결된 캐릭터입니다.');this.statement('UPDATE profiles SET username=?,salt=?,digest=?,token_hash=? WHERE id=?').run(username,salt,digest,hash(token),guestId);return guestId;}const p=this.normalize({id:crypto.randomUUID(),name:cleanName(name)});this.statement('INSERT INTO profiles VALUES(?,?,?,?,?,?)').run(p.id,hash(token),username,salt,digest,JSON.stringify(p));return p.id;});return {profile:this.public(id),token};
 }
 async authenticate(username,password){username=accountName(username);passwordCheck(password);const r=this.statement('SELECT * FROM profiles WHERE username=?').get(username),salt=r?.salt||'00000000000000000000000000000000',key=await scrypt(password,salt,64);if(!r||!crypto.timingSafeEqual(key,Buffer.from(r.digest,'hex')))throw Error('계정 ID 또는 비밀번호를 확인하세요.');const token=crypto.randomBytes(32).toString('base64url');this.transaction(()=>this.statement('UPDATE profiles SET token_hash=? WHERE id=?').run(hash(token),r.id));return {profile:this.public(r.id),token};}
 revoke(id){this.transaction(()=>this.statement('UPDATE profiles SET token_hash=? WHERE id=?').run(hash(crypto.randomBytes(32)),id));}
 award(run,ids,arena,rewards){return this.transaction(()=>{const result={};for(const id of new Set(ids)){if(this.statement('SELECT 1 FROM receipts WHERE run=? AND player=?').get(run,id))continue;const p=this.get(id);p.gold+=rewards.gold;p.xp+=600;p.clears[arena]=(p.clears[arena]||0)+1;for(const [item,n]of rewards.items)p.items[item]=(p.items[item]||0)+n;this.put(p);this.statement('INSERT INTO receipts VALUES(?,?)').run(run,id);result[id]=this.public(id);}return result;});}
 shop(){return [...C.shop.filter(i=>i.buy&&i.id.startsWith('m_')).map(i=>({id:i.id,price:i.buy})),...C.equipment.filter(i=>i.type==='armor'||i.type==='acc').map(i=>({id:i.id,price:i.price}))];}
 purchase(id,item,quantity){integer(quantity,99);const offer=this.shop(this.get(id).character).find(i=>i.id===item);if(!offer)throw Error('판매하지 않는 물품입니다.');return this.transaction(()=>{const p=this.get(id),cost=offer.price*quantity;if(p.gold<cost)throw Error('골드가 부족합니다.');p.gold-=cost;p.items[item]=(p.items[item]||0)+quantity;this.put(p);return this.public(id);});}
 equip(id,item){const definition=C.equipment.find(i=>i.id===item);if(!definition||!['armor','acc'].includes(definition.type))throw Error('착용할 수 없는 장비입니다.');return this.transaction(()=>{const p=this.get(id);if(!(p.items[item]>0))throw Error('보유하지 않은 장비입니다.');p.equipment[definition.slot]=item;this.put(p);return this.public(id);});}
 market(){return this.statement('SELECT l.*,json_extract(p.data,\'$.name\') AS name FROM listings l JOIN profiles p ON p.id=l.seller ORDER BY created DESC,id LIMIT 200').all();}
 list(id,item,quantity,price){integer(quantity,999);integer(price,1000000);if(!C.materials.some(i=>i.id===item))throw Error('현재 거래소에서는 재료만 거래할 수 있습니다.');return this.transaction(()=>{const p=this.get(id);if(!(p.items[item]>=quantity))throw Error('보유 수량이 부족합니다.');if(this.statement('SELECT count(*) AS n FROM listings WHERE seller=?').get(id).n>=10)throw Error('판매 등록은 최대 10개입니다.');if(this.statement('SELECT count(*) AS n FROM listings').get().n>=200)throw Error('거래소 등록 한도에 도달했습니다.');p.items[item]-=quantity;this.put(p);const listing={id:crypto.randomUUID(),seller:id,item,quantity,price,created:Date.now()};this.statement('INSERT INTO listings VALUES(?,?,?,?,?,?)').run(...Object.values(listing));return listing;});}
 buy(id,listingId){return this.transaction(()=>{const l=this.statement('SELECT * FROM listings WHERE id=?').get(listingId);if(!l)throw Error('이미 판매되었거나 취소된 물품입니다.');if(l.seller===id)throw Error('자신의 물품은 구매할 수 없습니다.');const buyer=this.get(id),seller=this.get(l.seller),total=l.quantity*l.price;if(buyer.gold<total)throw Error('골드가 부족합니다.');if(!Number.isSafeInteger(seller.gold+total))throw Error('거래 금액 한도를 초과했습니다.');buyer.gold-=total;seller.gold+=total;buyer.items[l.item]=(buyer.items[l.item]||0)+l.quantity;this.put(buyer);this.put(seller);this.statement('DELETE FROM listings WHERE id=?').run(l.id);this.statement('INSERT INTO trades(listing,buyer,seller,item,quantity,total,created) VALUES(?,?,?,?,?,?,?)').run(l.id,id,l.seller,l.item,l.quantity,total,Date.now());return [this.public(id),this.public(l.seller)];});}
 cancel(id,listingId){return this.transaction(()=>{const l=this.statement('SELECT * FROM listings WHERE id=? AND seller=?').get(listingId,id);if(!l)throw Error('취소할 수 없는 물품입니다.');const p=this.get(id);p.items[l.item]=(p.items[l.item]||0)+l.quantity;this.put(p);this.statement('DELETE FROM listings WHERE id=?').run(l.id);return this.public(id);});}
 get data(){const profiles={};for(const r of this.statement('SELECT id FROM profiles').all())profiles[r.id]={...this.get(r.id),receipts:this.statement('SELECT run FROM receipts WHERE player=?').all(r.id).map(r=>r.run)};return {version:2,profiles};}
 close(){this.db.close();}
}
require('./rpg-store.cjs').install(Store);
module.exports={Store,cleanName};
