// Run backup against a live database. Restore only while the game server is stopped.
const fs=require('node:fs'),path=require('node:path');
const {DatabaseSync,backup}=require('node:sqlite');
async function main(){const [command,arg,confirmation]=process.argv.slice(2),directory=process.env.DATA_DIR||path.resolve(__dirname,'../.party-data'),file=path.join(directory,'world.sqlite');
 if(command==='backup'){const target=path.resolve(arg||path.join(directory,'backups','manual-'+Date.now()+'.sqlite'));if(!fs.existsSync(file))throw Error('저장 DB가 없습니다.');if(fs.existsSync(target))throw Error('새 백업 파일명을 지정하세요.');fs.mkdirSync(path.dirname(target),{recursive:true,mode:0o700});const db=new DatabaseSync(file);try{await backup(db,target);fs.chmodSync(target,0o600);}finally{db.close();}console.log('백업 완료: '+target);return;}
 if(command==='verify'){const source=path.resolve(arg||file);if(!fs.existsSync(source))throw Error('파일이 없습니다.');const db=new DatabaseSync(source,{readOnly:true});try{const check=db.prepare('PRAGMA integrity_check').get();if(Object.values(check)[0]!=='ok')throw Error('DB 무결성 확인 실패');console.log('무결성 정상 · 계정 '+db.prepare('SELECT count(*) n FROM profiles').get().n+'개');}finally{db.close();}return;}
 if(command==='restore'){if(!arg||confirmation!=='--server-stopped')throw Error('서버를 종료한 후 restore <백업 파일> --server-stopped 로 실행하세요.');const source=path.resolve(arg);if(source===file||!fs.existsSync(source))throw Error('다른 백업 파일을 선택하세요.');const db=new DatabaseSync(source,{readOnly:true});try{if(Object.values(db.prepare('PRAGMA integrity_check').get())[0]!=='ok')throw Error('DB 무결성 확인 실패');db.prepare('SELECT count(*) FROM profiles').get();}finally{db.close();}fs.mkdirSync(directory,{recursive:true,mode:0o700});const archive=path.join(directory,'before-restore-'+Date.now());fs.mkdirSync(archive,{mode:0o700});for(const suffix of ['', '-wal','-shm'])if(fs.existsSync(file+suffix))fs.renameSync(file+suffix,path.join(archive,'world.sqlite'+suffix));fs.copyFileSync(source,file);fs.chmodSync(file,0o600);console.log('복구 완료. 이전 DB 보관: '+archive);return;}
 throw Error('사용법: node tools/party-backup.cjs backup [파일] | verify [파일] | restore <파일> --server-stopped');
}
main().catch(e=>{console.error(e.message);process.exitCode=1;});
