const WIRE=require('../js/party-wire.js');
const {fork}=require('node:child_process'),fs=require('node:fs'),path=require('node:path'),os=require('node:os'),assert=require('node:assert/strict'),{WebSocket}=require('ws');
const directory=fs.mkdtempSync(path.join(os.tmpdir(),'tw-load-')),worker=fork(path.join(__dirname,'party-load-worker.cjs'),[directory],{stdio:['ignore','ignore','inherit','ipc']}),people=[],timers=[];
const ipc=type=>new Promise((resolve,reject)=>{const deadline=setTimeout(()=>{worker.off('message',handler);reject(Error('IPC timeout '+type));},10000);const handler=m=>{if(m.type===type){clearTimeout(deadline);worker.off('message',handler);resolve(m);}};worker.on('message',handler);});
const command=async type=>{const pending=ipc(type);worker.send({type});return pending;};
const pause=ms=>new Promise(r=>setTimeout(r,ms));
async function client(url,index){const ws=new WebSocket(url),waiters=[];let seq=0;const p={ws,index,profile:null,state:null,latency:[],errors:[],unexpectedClose:false,chatReceived:0};p.next=match=>new Promise((resolve,reject)=>{const w={match,resolve,timer:setTimeout(()=>{waiters.splice(waiters.indexOf(w),1);reject(Error('timeout '+index));},7000)};waiters.push(w);});p.send=m=>ws.send(JSON.stringify({seq:++seq,...m}));ws.on('message',bytes=>{let m=JSON.parse(bytes);if(m.type==='patch')m=WIRE.apply(p.state,m.patch);if(m.type==='state')p.state=m;if(m.type==='profile')p.profile=m.profile;if(m.type==='pong')p.latency.push(performance.now()-m.echo);if(m.type==='error')p.errors.push(m.message);if(m.type==='chat')p.chatReceived++;for(const w of [...waiters])if(w.match(m)){clearTimeout(w.timer);waiters.splice(waiters.indexOf(w),1);w.resolve(m);}});ws.on('error',e=>p.errors.push(e.message));ws.on('close',()=>p.unexpectedClose=true);await new Promise(r=>ws.once('open',r));const hello=p.next(m=>m.type==='welcome'||m.type==='error');p.send({type:'hello'});p.welcome=await hello;if(p.welcome.type==='error')return p;const name=p.next(m=>m.type==='profile');p.send({type:'character',name:'부하검증_'+String(index).padStart(3,'0')});await name;return p;}
function percentile(a,q){return a.slice().sort((a,b)=>a-b)[Math.min(a.length-1,Math.floor(a.length*q))]||0;}
async function measure(name,ms){for(const p of people)p.latency=[];await command('reset');await pause(ms);const stats=await command('stats'),latencies=people.flatMap(p=>p.latency);return {name,...stats,pingSamples:latencies.length,pingP50Ms:percentile(latencies,.5),pingP95Ms:percentile(latencies,.95),pingMaxMs:Math.max(...latencies),sentMBPerSecond:stats.bytesSent/1048576/stats.seconds};}
(async()=>{try{
 const {port}=await ipc('ready'),url=`ws://127.0.0.1:${port}/party-socket`;
 for(let i=0;i<100;i++)people.push(await client(url,i));assert.ok(people.every(p=>p.profile?.characterCreated));
 const extra=await client(url,101);assert.equal(extra.welcome.type,'error');assert.match(extra.welcome.message,/가득/);extra.ws.terminate();
 timers.push(setInterval(()=>{for(const p of people)p.send({type:'ping',time:performance.now()});},250));
 timers.push(setInterval(()=>{for(const p of people)p.send({type:'chat',channel:'world',text:'부하 검증 '+p.index});},1600));
 const phases=[await measure('100 online: shelter/office + world chat',4000)];
 for(let i=0;i<100;i+=4){const leader=people[i],made=leader.next(m=>m.type==='state');leader.send({type:'create',level:['d01','d02','d03'][(i/4)%3]});const room=await made;for(const p of people.slice(i+1,i+4)){const joined=p.next(m=>m.type==='state');p.send({type:'join',code:room.code});await joined;}const ready=leader.next(m=>m.type==='state'&&m.members.length===4&&m.members.every(p=>p.ready));for(const p of people.slice(i,i+4))p.send({type:'ready',ready:true});await ready;const start=leader.next(m=>m.type==='state'&&m.raid);leader.send({type:'start'});await start;}
 await command('fight');assert.equal(new Set(people.map(p=>p.state.raid.id)).size,25);
 timers.push(setInterval(()=>{for(const p of people){const r=p.state?.raid;if(!r||r.state!=='fight')continue;const me=r.players.find(x=>x.id===p.profile.id);if(me.hp<=0)continue;const dx=r.boss.x-me.x,dy=(r.boss.y-me.y)/.55,d=Math.hypot(dx,dy);p.send({type:'move',x:d>115?dx:0,y:d>115?dy:0});if(r.boss.state==='telegraph'&&r.boss.tele<.17)p.send({type:r.boss.pattern.counterable?'attack':'dodge'});else if(!me.action&&r.boss.state!=='telegraph')p.send({type:'attack'});}},100));
 phases.push(await measure('100 online: 25 independent four-player boss fights + world chat',10000));
 assert.ok(phases[1].damage>0);assert.ok(phases.every(p=>p.online===100));assert.ok(people.every(p=>!p.unexpectedClose&&p.errors.length===0),people.flatMap(p=>p.errors).join(','));assert.ok(people.every(p=>p.chatReceived>0));
 const report={date:new Date().toISOString(),node:process.version,platform:os.platform(),cpu:os.cpus()[0]?.model,logicalCpus:os.availableParallelism(),target:100,connections:100,extraConnection:'rejected',connectionsLost:0,protocolErrors:0,phases,limitations:['Loopback networking: not internet latency or Render capacity.','Separate server/client processes on one development machine.','Guest token sessions; registration/password hashing tested separately.','Boss spawn positions are set by benchmark-only IPC; all combat actions use real WebSockets.','10-second combat sample; not a long soak, GPU/mobile or 100-human playtest.']};
 fs.mkdirSync(path.join(__dirname,'../docs/validation'),{recursive:true});fs.writeFileSync(path.join(__dirname,'../docs/validation/party-load-100.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report,null,2));
 }finally{timers.forEach(clearInterval);for(const p of people)p.ws.terminate();if(worker.connected){worker.send({type:'stop'});await new Promise(r=>worker.once('exit',r));}fs.rmSync(directory,{recursive:true,force:true});}})().catch(e=>{console.error(e);worker.kill();process.exitCode=1;});
